# Generated by Django 5.1.3 on 2025-07-18 21:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre único de la sala', max_length=100, unique=True)),
                ('ubicacion', models.CharField(help_text='Ubicación física de la sala', max_length=200)),
                ('capacidad', models.PositiveIntegerField(help_text='Número máximo de personas que puede albergar', validators=[django.core.validators.MinValueValidator(1)])),
                ('foto', models.ImageField(blank=True, help_text='Foto de referencia de la sala', null=True, upload_to='intranet/salas/')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva'), ('mantenimiento', 'En Mantenimiento')], default='activa', help_text='Estado actual de la sala', max_length=20)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional de la sala')),
                ('equipamiento', models.TextField(blank=True, help_text='Equipamiento disponible (proyector, pizarra, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(help_text='Título de la reunión', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la reunión')),
                ('fecha_inicio', models.DateTimeField(help_text='Fecha y hora de inicio')),
                ('fecha_fin', models.DateTimeField(help_text='Fecha y hora de fin')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='activa', help_text='Estado de la reserva', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario_creador', models.ForeignKey(help_text='Usuario que creó la reserva', on_delete=django.db.models.deletion.CASCADE, related_name='reservas_creadas', to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(help_text='Sala reservada', on_delete=django.db.models.deletion.CASCADE, to='intranet.sala')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('invitacion', 'Invitación'), ('recordatorio', 'Recordatorio'), ('cancelacion', 'Cancelación'), ('modificacion', 'Modificación')], help_text='Tipo de notificación', max_length=20)),
                ('email_enviado', models.EmailField(help_text='Email al que se envió', max_length=254)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('error', 'Error'), ('pendiente', 'Pendiente')], default='pendiente', help_text='Estado del envío', max_length=20)),
                ('error_mensaje', models.TextField(blank=True, help_text='Mensaje de error si falló el envío')),
                ('destinatario', models.ForeignKey(help_text='Usuario destinatario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reserva', models.ForeignKey(help_text='Reserva relacionada', on_delete=django.db.models.deletion.CASCADE, to='intranet.reserva')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado_asistencia', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('declinado', 'Declinado'), ('asistio', 'Asistió'), ('no_asistio', 'No Asistió')], default='pendiente', help_text='Estado de confirmación de asistencia', max_length=20)),
                ('fecha_invitacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(help_text='Usuario participante', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reserva', models.ForeignKey(help_text='Reserva a la que pertenece', on_delete=django.db.models.deletion.CASCADE, to='intranet.reserva')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'ordering': ['fecha_invitacion'],
                'unique_together': {('reserva', 'usuario')},
            },
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['sala', 'fecha_inicio', 'fecha_fin'], name='intranet_re_sala_id_87758b_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['usuario_creador', 'fecha_inicio'], name='intranet_re_usuario_03a577_idx'),
        ),
    ]
