# Generated by Django 5.1.3 on 2025-07-11 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Proyecto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('pausado', 'Pausado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='activo', max_length=20, verbose_name='Estado')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Módulo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='proyectos.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['nombre'],
                'unique_together': {('proyecto', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Test Case')),
                ('descripcion', models.TextField(verbose_name='Descripción del Test Case')),
                ('pasos_prueba', models.TextField(verbose_name='Pasos de la Prueba')),
                ('resultado_esperado', models.TextField(verbose_name='Resultado Esperado')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10, verbose_name='Prioridad')),
                ('resultado', models.CharField(choices=[('pendiente', 'Pendiente'), ('exitoso', 'Exitoso'), ('fallido', 'Fallido'), ('solicitud_revision', 'Solicitud de Revisión')], default='pendiente', max_length=20, verbose_name='Resultado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_ejecucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Ejecución')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Resolución')),
                ('comentarios', models.TextField(blank=True, verbose_name='Comentarios')),
                ('resuelto', models.BooleanField(default=False, verbose_name='Resuelto')),
                ('desarrollador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pruebas_desarrollo', to=settings.AUTH_USER_MODEL, verbose_name='Desarrollador')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas', to='proyectos.modulo', verbose_name='Módulo')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas', to='proyectos.proyecto', verbose_name='Proyecto')),
                ('tester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pruebas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Tester')),
            ],
            options={
                'verbose_name': 'Prueba',
                'verbose_name_plural': 'Pruebas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ProyectoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('tester', 'Tester'), ('desarrollador', 'Desarrollador')], max_length=15, verbose_name='Rol')),
                ('fecha_invitacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Invitación')),
                ('fecha_aceptacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aceptación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_invitados', to='proyectos.proyecto', verbose_name='Proyecto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_invitado', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Usuario del Proyecto',
                'verbose_name_plural': 'Usuarios del Proyecto',
                'ordering': ['-fecha_invitacion'],
                'unique_together': {('proyecto', 'usuario')},
            },
        ),
    ]
