# Generated by Django 5.1.3 on 2025-07-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='archivos_adjuntos',
            field=models.FileField(blank=True, help_text='Screenshots, logs, o documentos relacionados con la prueba', null=True, upload_to='proyectos/pruebas/archivos/', verbose_name='Archivos Adjuntos'),
        ),
    ]
