# Generated by Django 5.1.3 on 2025-07-15 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_prueba_archivos_adjuntos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prueba',
            name='archivos_adjuntos',
        ),
        migrations.CreateModel(
            name='ArchivoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='Screenshots, logs, o documentos relacionados con la prueba', upload_to='proyectos/pruebas/archivos/', verbose_name='Archivo')),
                ('nombre_original', models.CharField(help_text='Nombre original del archivo', max_length=255, verbose_name='Nombre Original')),
                ('descripcion', models.CharField(blank=True, help_text='Descripción opcional del archivo', max_length=500, verbose_name='Descripción')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_adjuntos', to='proyectos.prueba', verbose_name='Prueba')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Archivo Adjunto',
                'verbose_name_plural': 'Archivos Adjuntos',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
