databases:
  - name: pacifico
    plan: free
    databaseName: backup_ykk0
    user: backup_ykk0_user
    password: oJc6znaX6FVm7dvc7qC4XAKNtEvAPrBt
    host: dpg-cuh945btq21c73f8tkg0-a
    port: 5432

services:
  - type: web
    plan: free
    name: pacifico
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn financiera.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pacifico
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4