# Generated by Django 5.1.3 on 2025-04-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Celulares",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("numero", models.CharField(max_length=20, unique=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                ("marca", models.CharField(max_length=50)),
                ("modelo", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "celulares",
            },
        ),
    ]
