# Generated by Django 5.1.3 on 2025-04-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tombola", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="celulares",
            name="color",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
