# Generated by Django 5.1.3 on 2025-04-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tombola', '0002_celulares_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tombola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tombola',
            },
        ),
    ]
