# Generated by Django 5.1.3 on 2025-04-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tombola', '0003_tombola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tombola',
            name='fecha_evento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
