# Generated by Django 5.1.3 on 2025-04-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tombola', '0005_boleto'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioTombola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=100, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, choices=[('Sector público', 'Sector público'), ('Empresa privada', 'Empresa privada'), ('Jubilado', 'Jubilado'), ('Independiente', 'Independiente')], max_length=100, null=True)),
                ('salario', models.CharField(blank=True, choices=[('Menor a $850.00', 'Menor a $850.00'), ('Entre $850.00 y $1,000.00', 'Entre $850.00 y $1,000.00'), ('Mayor que $1,000.00 hasta $2,000.00', 'Mayor que $1,000.00 hasta $2,000.00'), ('Mayor a $2,000.00', 'Mayor a $2,000.00'), ('Menor a $600.00', 'Menor a $600.00'), ('Entre $600.00 y $850.00', 'Entre $600.00 y $850.00')], max_length=50, null=True)),
                ('garantia', models.BooleanField(default=False)),
                ('es_cliente', models.BooleanField(default=False)),
                ('producto_interesado', models.CharField(blank=True, choices=[('Préstamos personal', 'Préstamos personal'), ('Préstamo personal con garantía hipotecaria', 'Préstamo personal con garantía hipotecaria'), ('Préstamo de auto', 'Préstamo de auto'), ('Préstamo para independiente o microempresario', 'Préstamo para independiente o microempresario')], max_length=100, null=True)),
                ('dinero_a_solicitar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('autorizacion_apc', models.BooleanField(default=False)),
                ('acepta_condiciones', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'formulario_tombola',
            },
        ),
    ]
