# Generated by Django 5.1.3 on 2025-04-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tombola', '0006_formulariotombola'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='canalOrigen',
            field=models.CharField(blank=True, choices=[('Formulario', 'Formulario'), ('Carga masiva', 'Carga masiva')], max_length=50, null=True),
        ),
    ]
