# Generated by Django 5.1.3 on 2025-04-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tombola', '0007_boleto_canalorigen'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulariotombola',
            name='oficial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
