# Generated by Django 5.1.3 on 2025-04-10 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tombola', '0008_formulariotombola_oficial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulariotombola',
            name='tombola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formularios', to='tombola.tombola'),
        ),
    ]
