# Generated by Django 5.1.3 on 2025-04-14 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0120_remove_cliente_apcpi_remove_cliente_apcscore_and_more"),
        ("tombola", "0009_formulariotombola_tombola"),
    ]

    operations = [
        migrations.AddField(
            model_name="boleto",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boletos",
                to="pacifico.cliente",
            ),
        ),
    ]
