# Generated by Django 5.1.3 on 2025-04-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tombola", "0011_delete_celulares_formulariotombola_sexo"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulariotombola",
            name="cedulaCliente",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
