# Generated by Django 5.1.3 on 2025-04-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tombola", "0012_formulariotombola_cedulacliente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulariotombola",
            name="producto_interesado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Préstamos personal", "Préstamos personal"),
                    ("Préstamo de auto", "Préstamo de auto"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
