# Generated by Django 5.1.3 on 2025-04-16 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tombola", "0014_remove_formulariotombola_es_cliente_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulariotombola",
            name="tombola",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="formularios",
                to="tombola.tombola",
            ),
        ),
    ]
