# Generated by Django 5.1.3 on 2025-04-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tombola', '0015_alter_formulariotombola_tombola'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulariotombola',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
