# Generated by Django 5.1.3 on 2025-06-08 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tombola', '0018_alter_formulariotombola_oficial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulariotombola',
            name='boleto_asociado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formulario_origen', to='tombola.boleto'),
        ),
    ]
