# Generated by Django 5.1.3 on 2025-06-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tombola', '0019_formulariotombola_boleto_asociado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariotombola',
            name='salario',
            field=models.CharField(blank=True, choices=[('Menor a $600.00', 'Menor a $600.00'), ('Entre $600.00 y $850.00', 'Entre $600.00 y $850.00'), ('Menor a $850.00', 'Menor a $850.00'), ('Entre $850.00 y $1,000.00', 'Entre $850.00 y $1,000.00'), ('Mayor que $1,000.00 hasta $2,000.00', 'Mayor que $1,000.00 hasta $2,000.00'), ('Mayor a $2,000.00', 'Mayor a $2,000.00')], max_length=50, null=True),
        ),
    ]
