# Generated by Django 5.1.3 on 2025-06-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tombola', '0020_alter_formulariotombola_salario'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaMasiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.CharField(max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('cantidad_registros', models.IntegerField()),
                ('usuario', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'carga_masiva',
            },
        ),
    ]
