# Generated by Django 5.1.3 on 2025-06-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tombola', '0021_cargamasiva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargamasiva',
            name='archivo',
            field=models.FileField(upload_to='cargas_masivas/'),
        ),
    ]
