# Generated by Django 5.1.5 on 2025-04-21 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivoadicional',
            name='curso',
        ),
        migrations.AddField(
            model_name='archivoadicional',
            name='tema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='capacitaciones_app.tema'),
            preserve_default=False,
        ),
    ]
