# Generated by Django 5.1.3 on 2025-05-08 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "capacitaciones_app",
            "0002_remove_archivoadicional_curso_archivoadicional_tema",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pregunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField()),
                ("puntaje", models.PositiveIntegerField(default=0)),
                (
                    "archivo",
                    models.FileField(
                        blank=True, null=True, upload_to="archivos_preguntas/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Opcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(max_length=255)),
                ("es_correcta", models.BooleanField(default=False)),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opciones",
                        to="capacitaciones_app.pregunta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("instrucciones", models.TextField(blank=True, null=True)),
                (
                    "portada",
                    models.ImageField(
                        blank=True, null=True, upload_to="quiz_portadas/"
                    ),
                ),
                (
                    "modulo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="capacitaciones_app.modulo",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pregunta",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preguntas",
                to="capacitaciones_app.quiz",
            ),
        ),
        migrations.CreateModel(
            name="RespuestaUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opcion_seleccionada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="capacitaciones_app.opcion",
                    ),
                ),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="capacitaciones_app.pregunta",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResultadoQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puntaje", models.IntegerField()),
                ("aprobado", models.BooleanField(default=False)),
                ("fecha_realizacion", models.DateTimeField(auto_now_add=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="capacitaciones_app.quiz",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "puntuacion",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 ⭐"),
                            (2, "2 ⭐"),
                            (3, "3 ⭐"),
                            (4, "4 ⭐"),
                            (5, "5 ⭐"),
                        ],
                        verbose_name="Calificación",
                    ),
                ),
                ("comentario", models.TextField(blank=True, verbose_name="Comentario")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "tema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="capacitaciones_app.tema",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-creado_en"],
                "unique_together": {("usuario", "tema")},
            },
        ),
    ]
