# Generated by Django 5.1.3 on 2025-05-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "capacitaciones_app",
            "0003_pregunta_opcion_quiz_pregunta_quiz_respuestausuario_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="fecha_fin",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="curso",
            name="fecha_inicio",
            field=models.DateField(blank=True, null=True),
        ),
    ]
