# Generated by Django 5.1.3 on 2025-05-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones_app', '0004_alter_curso_fecha_fin_alter_curso_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='video_externo',
            field=models.TextField(blank=True, help_text='Pega aquí un iframe o un link de Vimeo, OneDrive, Google Drive, etc.', null=True, verbose_name='Embed o link de video externo'),
        ),
    ]
