# Generated by Django 5.1.3 on 2025-05-18 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones_app', '0005_tema_video_externo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='usuarios_asignados',
            field=models.ManyToManyField(blank=True, related_name='cursos_asignados', to=settings.AUTH_USER_MODEL),
        ),
    ]
