# Generated by Django 5.1.3 on 2025-05-19 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones_app', '0007_grupoasignacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupoasignacion',
            old_name='miembros',
            new_name='usuarios_asignados',
        ),
    ]
