# Generated by Django 5.1.3 on 2025-06-20 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones_app', '0010_encuestasatisfaccioncurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuestasatisfaccioncurso',
            name='lugar',
            field=models.CharField(choices=[('En la Oficina/Sucursal (puesto, sala de reunión)', 'En la Oficina/Sucursal (puesto, sala de reunión)'), ('En la Casa', 'En la Casa'), ('En el transporte público/privado', 'En el transporte público/privado')], max_length=50),
        ),
    ]
