# Generated by Django 5.1.3 on 2025-06-20 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones_app', '0011_alter_encuestasatisfaccioncurso_lugar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EncuestaSatisfaccionCurso',
        ),
    ]
