# Generated by Django 5.1.3 on 2025-06-20 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones_app', '0012_delete_encuestasatisfaccioncurso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncuestaSatisfaccionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(choices=[('CONTABILIDAD', 'CONTABILIDAD'), ('COBROS', 'COBROS'), ('CÓMPUTO', 'CÓMPUTO'), ('EXPERIENCIA AL CLIENTE', 'EXPERIENCIA AL CLIENTE'), ('FINANZAS', 'FINANZAS'), ('GERENCIA', 'GERENCIA'), ('ITICO', 'ITICO'), ('LEGAL', 'LEGAL'), ('NEGOCIOS', 'NEGOCIOS'), ('PROCESOS', 'PROCESOS'), ('RECURSOS HUMANOS- ADM', 'RECURSOS HUMANOS- ADM'), ('SERVICIOS GENERALES', 'SERVICIOS GENERALES'), ('TRAMITE', 'TRAMITE')], max_length=40)),
                ('cargo', models.CharField(choices=[('Asistente', 'Asistente'), ('Analista', 'Analista'), ('Oficial/Profesional', 'Oficial/Profesional'), ('Coordinador', 'Coordinador'), ('Encargada/Supervisor', 'Encargada/Supervisor'), ('Jefe', 'Jefe'), ('Gerente', 'Gerente')], max_length=30)),
                ('expositor', models.PositiveSmallIntegerField()),
                ('utilidad', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], max_length=2)),
                ('satisfaccion', models.PositiveSmallIntegerField()),
                ('aprendido', models.TextField(max_length=300)),
                ('lugar', models.CharField(choices=[('En la Oficina/Sucursal (puesto, sala de reunión)', 'En la Oficina/Sucursal (puesto, sala de reunión)'), ('En la Casa', 'En la Casa'), ('En el transporte público/privado', 'En el transporte público/privado')], max_length=50)),
                ('rol', models.CharField(choices=[('Participante', 'Participante'), ('Expositor', 'Expositor'), ('Organizador', 'Organizador'), ('Otro', 'Otro')], max_length=20)),
                ('recomendacion', models.TextField(blank=True, max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
