# Generated by Django 5.1.3 on 2025-06-20 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones_app', '0013_encuestasatisfaccioncurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresocurso',
            name='encuesta_completada',
            field=models.BooleanField(default=False),
        ),
    ]
