# Generated by Django 5.1.3 on 2025-06-20 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones_app', '0014_progresocurso_encuesta_completada'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuestasatisfaccioncurso',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='capacitaciones_app.curso'),
        ),
    ]
