# Generated by Django 5.1.3 on 2025-06-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones_app', '0015_encuestasatisfaccioncurso_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresocurso',
            name='certificado_descargado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progresocurso',
            name='fecha_descarga_certificado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
