# Generated by Django 5.1.3 on 2025-06-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones_app', '0016_progresocurso_certificado_descargado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='duracion_horas',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Duración estimada del curso en horas (ej: 8.5)', max_digits=5, null=True, verbose_name='Duración en horas'),
        ),
    ]
