# Generated by Django 5.1.3 on 2025-06-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones_app', '0017_curso_duracion_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuestasatisfaccioncurso',
            name='comentarios_curso',
            field=models.TextField(default='datatable', help_text='Comentarios sobre el curso o recomendaciones para mejorarlo', max_length=500),
            preserve_default=False,
        ),
    ]
