# Generated by Django 5.1.3 on 2025-06-24 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones_app', '0010_alter_grupoasignacion_usuarios_asignados_and_more'),
        ('capacitaciones_app', '0018_encuestasatisfaccioncurso_comentarios_curso'),
    ]

    operations = [
    ]
