# Generated by Django 5.1.3 on 2025-06-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones_app', '0019_merge_20250624_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='color_portada',
            field=models.CharField(default='#009c3c', help_text='Color hexadecimal para la portada (ej: #FFFFFF)', max_length=7),
        ),
    ]
