# Generated by Django 5.1.3 on 2025-06-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones_app', '0020_curso_color_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='tipo_curso',
            field=models.CharField(blank=True, choices=[('INDUCCION', 'Inducción Personal Nuevo Ingreso'), ('GESTION', 'Gestión Organizacional(CMA, Planeación Estratégica, Evaluación Desempeño, Políticas y Manuales internos)'), ('TECNICO', 'Técnico para el cargo (conocimiento técnico, procesos del área, ,cumplimiento, riesgos, etc)'), ('HERRAMIENTAS', 'Herramientas Técnicas( libre office, excel, software, power bi, visio, APPX, VIsio,etc)'), ('DESARROLLO', 'Desarrollo Personal/Habilidades Blandas (Competencias, personalidad, aptitudes, cualidades, manejo de estrés,etc)')], max_length=20, null=True, verbose_name='Tipo de curso'),
        ),
    ]
