# Generated by Django 5.1.3 on 2025-07-06 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones_app', '0022_grupoasignacion_supervisor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupoasignacion',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='grupoasignacion',
            name='supervisor_principal',
            field=models.ForeignKey(blank=True, limit_choices_to={'userprofile__rol': 'Supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_supervisados_principal', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor Principal'),
        ),
        migrations.AddField(
            model_name='grupoasignacion',
            name='supervisores_adicionales',
            field=models.ManyToManyField(blank=True, limit_choices_to={'userprofile__rol': 'Supervisor'}, related_name='grupos_supervisados_adicional', to=settings.AUTH_USER_MODEL, verbose_name='Supervisores Adicionales'),
        ),
    ]
