# Generated by Django 5.1.3 on 2025-07-09 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones_app', '0023_remove_grupoasignacion_supervisor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoasignacion',
            name='usuarios_asignados',
            field=models.ManyToManyField(limit_choices_to={'is_active': True}, related_name='grupos_asignados', to=settings.AUTH_USER_MODEL),
        ),
    ]
