# Generated by Django 5.1.3 on 2025-05-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patrono',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('agrupador', models.CharField(max_length=255)),
                ('selectDescuento', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('porServDesc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('montoFijo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('disketCentral', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
            ],
        ),
    ]
