# Generated by Django 5.1.3 on 2025-05-21 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrono',
            name='agrupador',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
