# Generated by Django 5.1.3 on 2025-05-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_alter_patrono_agrupador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activa', models.BooleanField(default=True)),
                ('producto', models.CharField(choices=[('PREST. AUTO', 'Prest. Auto'), ('PERSONAL', 'Personal')], max_length=20)),
                ('incentivo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('LETRAS', 'Letras'), ('BONO', 'Bono'), ('FECHA PAGO', 'Fecha Pago')], max_length=20)),
                ('dirigido_a', models.CharField(choices=[('CLIENTE', 'Cliente'), ('VENDEDOR', 'Vendedor'), ('AGENCIA', 'Agencia')], max_length=20)),
                ('tipo_vendedor', models.CharField(blank=True, max_length=255, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('no_letras', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='patrono',
            name='disketCentral',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, null=True),
        ),
    ]
