# Generated by Django 5.1.3 on 2025-05-22 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0003_promocion_alter_patrono_disketcentral'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetPromocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patcat', models.IntegerField()),
                ('agrupador', models.CharField(max_length=255)),
                ('todos', models.BooleanField(default=False)),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_promociones', to='mantenimiento.promocion')),
            ],
        ),
    ]
