# Generated by Django 5.1.3 on 2025-05-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0004_targetpromocion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocion',
            name='tipo_vendedor',
        ),
        migrations.AddField(
            model_name='promocion',
            name='vendedorTipo',
            field=models.CharField(blank=True, choices=[('SIN VENDEDOR', 'SIN VENDEDOR'), ('EXTERNO', 'EXTERNO'), ('CHISPA', 'CHISPA'), ('INTERNO', 'INTERNO'), ('SATELITE', 'SATELITE'), ('AGENCIAS', 'AGENCIAS')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='targetpromocion',
            name='agrupador',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='targetpromocion',
            name='patcat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
