# Generated by Django 5.1.3 on 2025-07-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0006_alter_promocion_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secuencia', models.IntegerField()),
                ('razon_social', models.CharField(max_length=255)),
            ],
        ),
    ]
