# Generated by Django 5.1.3 on 2024-12-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="cedulaCliente",
            field=models.CharField(default="0000000000", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="edad",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="fechaNacimiento",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="nombreCliente",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
