# Generated by Django 5.1.3 on 2024-12-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0002_cotizacion_cedulacliente_cotizacion_edad_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="comiCierre",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="fechaInicioPago",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="plazoPago",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="sexo",
            field=models.CharField(
                choices=[("MASCULINO", "Masculino"), ("FEMENINO", "Femenino")],
                default="MASCULINO",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="tasaInteres",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="cedulaCliente",
            field=models.CharField(default="", max_length=10, null=True),
        ),
    ]
