# Generated by Django 5.1.3 on 2024-12-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0004_cotizacion_montoprestamo"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="r_deseada",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
