# Generated by Django 5.1.3 on 2024-12-02 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0005_cotizacion_r_deseada"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodoPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("edad", models.IntegerField(null=True)),
                ("descripcion", models.CharField(max_length=100, null=True)),
                ("periocidad", models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="periodoPago",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pacifico.periodopago",
            ),
        ),
    ]
