# Generated by Django 5.1.3 on 2024-12-02 16:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0006_periodopago_cotizacion_periodopago"),
    ]

    operations = [
        migrations.RenameField(
            model_name="periodopago",
            old_name="edad",
            new_name="codigo",
        ),
    ]
