# Generated by Django 5.1.3 on 2024-12-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0007_rename_edad_periodopago_codigo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aseguradora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=100, null=True)),
                ("codigo", models.IntegerField(null=True)),
            ],
        ),
    ]
