# Generated by Django 5.1.3 on 2024-12-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0010_formpago_cotizacion_formapago"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="patrono",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
