# Generated by Django 5.1.3 on 2024-12-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0011_cotizacion_patrono"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="patronoCodigo",
            field=models.IntegerField(null=True),
        ),
    ]
