# Generated by Django 5.1.3 on 2024-12-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0012_cotizacion_patronocodigo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotizacion",
            name="formaPago",
            field=models.IntegerField(null=True),
        ),
    ]
