# Generated by Django 5.1.3 on 2024-12-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0013_alter_cotizacion_formapago"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotizacion",
            name="periodoPago",
            field=models.IntegerField(null=True),
        ),
    ]
