# Generated by Django 5.1.3 on 2024-12-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0014_alter_cotizacion_periodopago"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="vendedor",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="vendedorComision",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="periodoPago",
            field=models.IntegerField(default=1, null=True),
        ),
    ]
