# Generated by Django 5.1.3 on 2024-12-04 02:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0017_alter_cotizacion_cantpagosseguro_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotizacion",
            name="montoMensualSeguro",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="montoanualSeguro",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
