# Generated by Django 5.1.3 on 2024-12-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0018_alter_cotizacion_montomensualseguro_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="observaciones",
            field=models.TextField(blank=True, null=True),
        ),
    ]
