# Generated by Django 5.1.3 on 2024-12-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0019_cotizacion_observaciones"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="cartera",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="ingresos",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="licencia",
            field=models.CharField(
                choices=[("NO", "No"), ("SI", "Si")], default="SI", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="nombreEmpresa",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="perfilUniversitario",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="posicion",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="referenciasAPC",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="tiempoServicio",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
