# Generated by Django 5.1.3 on 2024-12-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0021_cotizacion_oficial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotizacion",
            name="cantPagosSeguro",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="mesesFinanciaSeguro",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
