# Generated by Django 5.1.3 on 2024-12-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0022_alter_cotizacion_cantpagosseguro_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="salarioBaseMensual",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
