# Generated by Django 5.1.3 on 2024-12-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0023_cotizacion_salariobasemensual"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotizacion",
            name="cartera",
            field=models.CharField(
                choices=[
                    ("CONTRALORÍA", "CONTRALORÍA"),
                    ("EMP. CSS", "EMP. CSS"),
                    ("AUTÓNOMAS", "AUTÓNOMAS"),
                    ("ACP", "ACP"),
                    ("JUBILADO CSS", "JUBILADO CSS"),
                    ("EMP. PRIVADA", "EMP. PRIVADA"),
                    ("JUBILADO DE LA ZONA", "JUBILADO DE LA ZONA"),
                    ("JUBI ACTIVO CONTRALORIA", "JUBI ACTIVO CONTRALORIA"),
                    ("JUBI ACTIVO CSS", "JUBI ACTIVO CSS"),
                    ("JUBILADO CONTRALORIA", "JUBILADO CONTRALORIA"),
                    ("JUBI ACTIVO AUTÓNOMA", "JUBI ACTIVO AUTÓNOMA"),
                    ("JUBILADO RIESGOS PROF. CSS", "JUBILADO RIESGOS PROF. CSS"),
                    ("INDEPENDIENTE", "INDEPENDIENTE"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
