# Generated by Django 5.1.3 on 2024-12-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0024_alter_cotizacion_cartera"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotizacion",
            name="vendedorComision",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, null=True
            ),
        ),
    ]
