# Generated by Django 5.1.3 on 2024-12-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0025_alter_cotizacion_vendedorcomision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotizacion",
            name="vendedor",
            field=models.CharField(
                default="1 - SIN VENDEDOR", max_length=255, null=True
            ),
        ),
    ]
