# Generated by Django 5.1.3 on 2024-12-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0026_alter_cotizacion_vendedor"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="sucursal",
            field=models.CharField(
                choices=[
                    ("2", "COLON"),
                    ("4", "CASINO"),
                    ("7", "DAVID"),
                    ("8", "CHORRERA"),
                    ("11", "SANTIAGO"),
                    ("13", "CALLE 50"),
                    ("16", "CHITRE"),
                    ("17", "PENONOME"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
