# Generated by Django 5.1.3 on 2024-12-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0027_cotizacion_sucursal"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="cashback",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="referenciasAPC",
            field=models.CharField(
                choices=[
                    ("BUENAS", "BUENAS"),
                    ("REGULARES", "REGULARES"),
                    ("MALAS", "MALAS"),
                    ("PESIMAS", "PESIMAS"),
                    ("SIN REFERENCIAS", "SIN REFERENCIAS"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
