# Generated by Django 5.1.3 on 2024-12-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0031_cotizacion_totalingresosadicionales"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotizacion",
            name="comiCierre",
            field=models.DecimalField(
                decimal_places=2, default=13, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="oficial",
            field=models.CharField(
                choices=[
                    ("TAIRA DE OBALDIA", "TAIRA DE OBALDIA"),
                    ("BLANCA VERGARA", "BLANCA VERGARA"),
                    ("MICHELLE SANTANA", "MICHELLE SANTANA"),
                    ("SHARLEN SAMANIEGO", "SHARLEN SAMANIEGO"),
                    ("ISIS BARRIA", "ISIS BARRIA"),
                    ("ILSA JIMÉNEZ", "ILSA JIMÉNEZ"),
                    ("MELISSA VEGA", "MELISSA VEGA"),
                    ("ESTEFANI FORD", "ESTEFANI FORD"),
                    ("CHARLEENE CARRERA", "CHARLEENE CARRERA"),
                    ("INISHELL MOSQUERA", "INISHELL MOSQUERA"),
                    ("JEMIMA CASTILLO", "JEMIMA CASTILLO"),
                    ("KENIA SIERRA", "KENIA SIERRA"),
                    ("YARINETH SANCHEZ", "YARINETH SANCHEZ"),
                    ("AMARELIS ALTAMIRANDA", "AMARELIS ALTAMIRANDA"),
                    ("DAVID ARAUZ", "DAVID ARAUZ"),
                    ("KRISTY KING", "KRISTY KING"),
                    ("YAJANIS CONCEPCIÓN", "YAJANIS CONCEPCIÓN"),
                    ("YEZKA AVILA", "YEZKA AVILA"),
                    ("MIGDALIA TEJEIRA", "MIGDALIA TEJEIRA"),
                    ("HANNY CISNEROS", "HANNY CISNEROS"),
                    ("YITZEL LÓPEZ", "YITZEL LÓPEZ"),
                    ("NELLY CAMAÑO", "NELLY CAMAÑO"),
                    ("DEYDA SALDAÑA", "DEYDA SALDAÑA"),
                    ("JAVIER CASTILLO", "JAVIER CASTILLO"),
                    ("ELINA DÍAZ", "ELINA DÍAZ"),
                    ("YARKELIS REYES", "YARKELIS REYES"),
                    ("STEPHANY SANDOVAL", "STEPHANY SANDOVAL"),
                    ("MARICRUZ ARMUELLES", "MARICRUZ ARMUELLES"),
                    ("LARISSA MARCIAGA", "LARISSA MARCIAGA"),
                    ("SHELUNSKA MASA", "SHELUNSKA MASA"),
                    ("ARGELIS GOMEZ", "ARGELIS GOMEZ"),
                    ("ROSMERY ANDRADE", "ROSMERY ANDRADE"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="r_deseada",
            field=models.DecimalField(
                decimal_places=2, default=14, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="totalIngresosAdicionales",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
