# Generated by Django 5.1.3 on 2024-12-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0033_pruebadario_alter_cotizacion_oficial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="jubilado",
            field=models.CharField(
                choices=[("SI", "Si"), ("NO", "No")], default="NO", max_length=10
            ),
        ),
    ]
