# Generated by Django 5.1.3 on 2024-12-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0034_cotizacion_jubilado"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="marcaAuto",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
