# Generated by Django 5.1.3 on 2024-12-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0035_cotizacion_marcaauto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cotizacion",
            name="marcaAuto",
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="marca",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="modelo",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="yearsFinanciamiento",
            field=models.IntegerField(default=1, null=True),
        ),
    ]
