# Generated by Django 5.1.3 on 2024-12-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0036_remove_cotizacion_marcaauto_cotizacion_marca_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="NumeroCotizacion",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
