# Generated by Django 5.1.3 on 2024-12-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0038_cotizacion_added_by_cotizacion_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="tasaEstimada",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
