# Generated by Django 5.1.3 on 2024-12-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0039_cotizacion_tasaestimada"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="tasaBruta",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
