# Generated by Django 5.1.3 on 2024-12-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0040_cotizacion_tasabruta"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="auxMonto2",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="r1",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="wrkMontoLetra",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
