# Generated by Django 5.1.3 on 2024-12-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0041_cotizacion_auxmonto2_cotizacion_r1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="calcComiCierreFinal",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="calcMontoNotaria",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="calcMontoTimbres",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="tablaTotalFeci",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="tablaTotalInteres",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="tablaTotalMontoCapital",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="tablaTotalPagos",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="tablaTotalSeguro",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
