# Generated by Django 5.1.3 on 2024-12-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0043_cotizacion_manejo_5porc"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cedulaCliente", models.CharField(max_length=255, null=True)),
                ("nombreCliente", models.CharField(max_length=255, null=True)),
                ("fechaNacimiento", models.DateField(null=True)),
                ("edad", models.IntegerField(null=True)),
                (
                    "sexo",
                    models.CharField(
                        choices=[("MASCULINO", "Masculino"), ("FEMENINO", "Femenino")],
                        default="MASCULINO",
                        max_length=10,
                    ),
                ),
                (
                    "jubilado",
                    models.CharField(
                        choices=[("SI", "Si"), ("NO", "No")],
                        default="NO",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
