# Generated by Django 5.1.3 on 2024-12-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0044_cliente"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="patrono",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
