# Generated by Django 5.1.3 on 2024-12-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0045_cliente_patrono"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="wrkLetraSeguro",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
