# Generated by Django 5.1.3 on 2024-12-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0047_cotizacion_wrkletrasinseguros"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="apcPI",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="apcScore",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="apcPI",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="apcScore",
            field=models.IntegerField(null=True),
        ),
    ]
