# Generated by Django 5.1.3 on 2024-12-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0048_cliente_apcpi_cliente_apcscore_cotizacion_apcpi_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="valorAuto",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
