# Generated by Django 5.1.3 on 2024-12-26 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0049_cotizacion_valorauto"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="aseguradora",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pacifico.aseguradora",
            ),
        ),
    ]
