# Generated by Django 5.1.3 on 2024-12-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0052_cliente_praadcto_cliente_praamonto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="dirOtros1",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="dirOtros2",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="dirOtros3",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="dirOtros4",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="dirOtrosDcto1",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cliente",
            name="dirOtrosDcto2",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cliente",
            name="dirOtrosDcto3",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cliente",
            name="dirOtrosDcto4",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cliente",
            name="dirOtrosMonto1",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="dirOtrosMonto2",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="dirOtrosMonto3",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="dirOtrosMonto4",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="dirOtros1",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="dirOtros2",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="dirOtros3",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="dirOtros4",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="dirOtrosDcto1",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="dirOtrosDcto2",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="dirOtrosDcto3",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="dirOtrosDcto4",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="dirOtrosMonto1",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="dirOtrosMonto2",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="dirOtrosMonto3",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="dirOtrosMonto4",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
