# Generated by Django 5.1.3 on 2024-12-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0053_cliente_dirotros1_cliente_dirotros2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="pagoVoluntario1",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="pagoVoluntario2",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="pagoVoluntario3",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="pagoVoluntario4",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="pagoVoluntario5",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="pagoVoluntario6",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="pagoVoluntarioDcto1",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cliente",
            name="pagoVoluntarioDcto2",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cliente",
            name="pagoVoluntarioDcto3",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cliente",
            name="pagoVoluntarioDcto4",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cliente",
            name="pagoVoluntarioDcto5",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cliente",
            name="pagoVoluntarioDcto6",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cliente",
            name="pagoVoluntarioMonto1",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="pagoVoluntarioMonto2",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="pagoVoluntarioMonto3",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="pagoVoluntarioMonto4",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="pagoVoluntarioMonto5",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="pagoVoluntarioMonto6",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="pagoVoluntario1",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="pagoVoluntario2",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="pagoVoluntario3",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="pagoVoluntario4",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="pagoVoluntario5",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="pagoVoluntario6",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="pagoVoluntarioDcto1",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="pagoVoluntarioDcto2",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="pagoVoluntarioDcto3",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="pagoVoluntarioDcto4",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="pagoVoluntarioDcto5",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="pagoVoluntarioDcto6",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="pagoVoluntarioMonto1",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="pagoVoluntarioMonto2",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="pagoVoluntarioMonto3",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="pagoVoluntarioMonto4",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="pagoVoluntarioMonto5",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="pagoVoluntarioMonto6",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
