# Generated by Django 5.1.3 on 2024-12-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0055_cliente_porsalarioneto_cliente_salariobasemensual_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="porSalarioNetoCompleto",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="salarioNetoActualCompleto",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="salarioNetoCompleto",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="totalDescuentosLegalesCompleto",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="totalIngresosAdicionales",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="totalIngresosMensualesCompleto",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="porSalarioNetoCompleto",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="salarioNetoActualCompleto",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="salarioNetoCompleto",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="totalDescuentosLegalesCompleto",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="totalIngresosMensualesCompleto",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
