# Generated by Django 5.1.3 on 2024-12-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0056_cliente_porsalarionetocompleto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="horasExtrasDcto",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cliente",
            name="horasExtrasMonto",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="primaDcto",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cliente",
            name="primaMonto",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="horasExtrasDcto",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="horasExtrasMonto",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="primaDcto",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="primaMonto",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
