# Generated by Django 5.1.3 on 2024-12-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0057_cliente_horasextrasdcto_cliente_horasextrasmonto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="bonosDcto",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cliente",
            name="bonosMonto",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="otrosDcto",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cliente",
            name="otrosMonto",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="bonosDcto",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="bonosMonto",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="otrosDcto",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="otrosMonto",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
