# Generated by Django 5.1.3 on 2024-12-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0060_cliente_mes0_cliente_mes1_cliente_mes10_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="primerMes",
            field=models.IntegerField(
                choices=[
                    (0, "Enero"),
                    (1, "Febrero"),
                    (2, "Marzo"),
                    (3, "Abril"),
                    (4, "Mayo"),
                    (5, "Junio"),
                    (6, "Julio"),
                    (7, "Agosto"),
                    (8, "Septiembre"),
                    (9, "Octubre"),
                    (10, "Noviembre"),
                    (11, "Diciembre"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="tipoProrrateo",
            field=models.CharField(
                choices=[
                    ("horas_extras", "Horas Extras"),
                    ("prima_produccion", "Prima de Producción"),
                ],
                default="horas_extras",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="primerMes",
            field=models.IntegerField(
                choices=[
                    (0, "Enero"),
                    (1, "Febrero"),
                    (2, "Marzo"),
                    (3, "Abril"),
                    (4, "Mayo"),
                    (5, "Junio"),
                    (6, "Julio"),
                    (7, "Agosto"),
                    (8, "Septiembre"),
                    (9, "Octubre"),
                    (10, "Noviembre"),
                    (11, "Diciembre"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="tipoProrrateo",
            field=models.CharField(
                choices=[
                    ("horas_extras", "Horas Extras"),
                    ("prima_produccion", "Prima de Producción"),
                ],
                default="horas_extras",
                max_length=20,
            ),
        ),
    ]
