# Generated by Django 5.1.3 on 2024-12-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0062_alter_cliente_primermes_alter_cotizacion_primermes"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="yearAuto",
            field=models.IntegerField(null=True),
        ),
    ]
