# Generated by Django 5.1.3 on 2024-12-27 17:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0063_cotizacion_yearauto"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cotizacion",
            old_name="yearAuto",
            new_name="yearCarro",
        ),
    ]
