# Generated by Django 5.1.3 on 2024-12-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0064_rename_yearauto_cotizacion_yearcarro"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="tipoDocumento",
            field=models.CharField(
                choices=[("CEDULA", "Cédula"), ("PASAPORTE", "Pasaporte")],
                default="CEDULA",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="tipoDocumento",
            field=models.CharField(
                choices=[("CEDULA", "Cédula"), ("PASAPORTE", "Pasaporte")],
                default="CEDULA",
                max_length=10,
            ),
        ),
    ]
