# Generated by Django 5.1.3 on 2024-12-31 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0065_cliente_tipodocumento_cotizacion_tipodocumento"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="kilometrajeAuto",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="nuevoAuto",
            field=models.CharField(
                choices=[("AUTO NUEVO", "Auto Nuevo"), ("AUTO USADO", "Auto Usado")],
                default="AUTO NUEVO",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="transmisionAuto",
            field=models.CharField(
                choices=[("MANUAL", "Manual"), ("AUTOMÁTICO", "Automático")],
                default="MANUAL",
                max_length=10,
                null=True,
            ),
        ),
    ]
