# Generated by Django 5.1.3 on 2025-01-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0067_remove_cotizacion_tasainteres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="apcPI",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=5, null=True
            ),
        ),
    ]
