# Generated by Django 5.1.3 on 2025-01-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0068_alter_cliente_apcpi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="horasExtrasMonto",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
