# Generated by Django 5.1.3 on 2025-01-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0069_alter_cliente_horasextrasmonto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="apcPI",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="porSalarioNeto",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="porSalarioNetoCompleto",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="abonoPorcentaje",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="apcPI",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="calcComiCierreFinal",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="calcMontoNotaria",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="calcMontoTimbres",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="comiCierre",
            field=models.DecimalField(
                decimal_places=2, default=13, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="porSalarioNeto",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="porSalarioNetoCompleto",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="r1",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="r_deseada",
            field=models.DecimalField(
                decimal_places=2, default=14, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="tasaBruta",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="tasaEstimada",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="vendedorComision",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="wrkLetraSeguro",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="wrkLetraSinSeguros",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="wrkMontoLetra",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
