# Generated by Django 5.1.3 on 2025-01-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0070_alter_cliente_apcpi_alter_cliente_porsalarioneto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotizacion",
            name="transmisionAuto",
            field=models.CharField(
                choices=[("MANUAL", "Manual"), ("AUTOMÁTICO", "Automático")],
                default="AUTOMÁTICO",
                max_length=10,
                null=True,
            ),
        ),
    ]
