# Generated by Django 5.1.3 on 2025-01-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0071_alter_cotizacion_transmisionauto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotizacion",
            name="transmisionAuto",
            field=models.CharField(
                choices=[("MANUAL", "Manual"), ("AUTOMÁTICO", "Automático")],
                default="AUTOMÁTICO",
                max_length=20,
                null=True,
            ),
        ),
    ]
