# Generated by Django 5.1.3 on 2025-01-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0072_alter_cotizacion_transmisionauto"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="montoManejoT",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
