# Generated by Django 5.1.3 on 2025-01-06 23:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0073_cotizacion_montomanejot"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="monto_manejo_b",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
