# Generated by Django 5.1.3 on 2025-01-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0074_cotizacion_monto_manejo_b"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="codeudorCedula",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="codeudorEmpresa",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="codeudorEstabilidad",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="codeudorIngresos",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="codeudorLicencia",
            field=models.CharField(
                choices=[("NO", "No"), ("SI", "Si")], default="SI", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="codeudorNombre",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="codeudorNombreEmpres1",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="codeudorNombreEmpres2",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="codeudorNombreEmpres3",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="codeudorPeriodo1",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="codeudorPeriodo2",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="codeudorPeriodo3",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="codeudorReferenciasAPC",
            field=models.CharField(
                choices=[
                    ("BUENAS", "BUENAS"),
                    ("REGULARES", "REGULARES"),
                    ("MALAS", "MALAS"),
                    ("PESIMAS", "PESIMAS"),
                    ("SIN REFERENCIAS", "SIN REFERENCIAS"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="codeudorSalario1",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="codeudorSalario2",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="codeudorSalario3",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
