# Generated by Django 5.1.3 on 2025-01-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "pacifico",
            "0075_cotizacion_codeudorcedula_cotizacion_codeudorempresa_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="aplicaCodeudor",
            field=models.CharField(
                choices=[("no", "No"), ("si", "Si")], default="no", max_length=2
            ),
        ),
    ]
