# Generated by Django 5.1.3 on 2025-01-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0077_cotizacion_cobonosdcto_cotizacion_cobonosmonto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="cototalIngresosAdicionales",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
