# Generated by Django 5.1.3 on 2025-01-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0079_cotizacion_codeudorcartera_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="coporSalarioNeto",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="coporSalarioNetoCompleto",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="cosalarioBaseMensual",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="cosalarioNeto",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="cosalarioNetoActual",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="cosalarioNetoActualCompleto",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="cosalarioNetoCompleto",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="cototalDescuentoDirecto",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="cototalDescuentosLegales",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="cototalDescuentosLegalesCompleto",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="cototalIngresosMensualesCompleto",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="cototalPagoVoluntario",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
