# Generated by Django 5.1.3 on 2025-01-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0080_cotizacion_coporsalarioneto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotizacion",
            name="financiaSeguro",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="vendedor",
            field=models.CharField(
                default="2 - VENDEDOR EN TRAMITE DE CODIGO", max_length=255, null=True
            ),
        ),
    ]
