# Generated by Django 5.1.3 on 2025-01-08 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0081_alter_cotizacion_financiaseguro_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotizacion",
            name="r_deseada",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="vendedorComision",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
