# Generated by Django 5.1.3 on 2025-01-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0082_alter_cotizacion_r_deseada_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotizacion",
            name="cantPagosSeguro",
            field=models.IntegerField(default=12, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="mesesFinanciaSeguro",
            field=models.IntegerField(default=3, null=True),
        ),
    ]
