# Generated by Django 5.1.3 on 2025-01-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0083_alter_cotizacion_cantpagosseguro_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotizacion",
            name="vendedor",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
