# Generated by Django 5.1.3 on 2025-01-10 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0084_alter_cotizacion_vendedor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sucursal",
                    models.CharField(
                        choices=[
                            ("2", "COLON"),
                            ("4", "CASINO"),
                            ("7", "DAVID"),
                            ("8", "CHORRERA"),
                            ("11", "SANTIAGO"),
                            ("13", "CALLE 50"),
                            ("16", "CHITRE"),
                            ("17", "PENONOME"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("auto_save_cotizaciones", models.BooleanField(default=False)),
                ("another_boolean_field", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
