# Generated by Django 5.1.3 on 2025-01-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0087_alter_cotizacion_oficial_alter_userprofile_oficial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="movPrimerMes",
            field=models.CharField(
                choices=[
                    ("ENERO", "ENERO"),
                    ("FEBRERO", "FEBRERO"),
                    ("MARZO", "MARZO"),
                    ("ABRIL", "ABRIL"),
                    ("MAYO", "MAYO"),
                    ("JUNIO", "JUNIO"),
                    ("JULIO", "JULIO"),
                    ("AGOSTO", "AGOSTO"),
                    ("SEPTIEMBRE", "SEPTIEMBRE"),
                    ("OCTUBRE", "OCTUBRE"),
                    ("NOVIEMBRE", "NOVIEMBRE"),
                    ("DICIEMBRE", "DICIEMBRE"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="movPrimerMes",
            field=models.CharField(
                choices=[
                    ("ENERO", "ENERO"),
                    ("FEBRERO", "FEBRERO"),
                    ("MARZO", "MARZO"),
                    ("ABRIL", "ABRIL"),
                    ("MAYO", "MAYO"),
                    ("JUNIO", "JUNIO"),
                    ("JULIO", "JULIO"),
                    ("AGOSTO", "AGOSTO"),
                    ("SEPTIEMBRE", "SEPTIEMBRE"),
                    ("OCTUBRE", "OCTUBRE"),
                    ("NOVIEMBRE", "NOVIEMBRE"),
                    ("DICIEMBRE", "DICIEMBRE"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
