# Generated by Django 5.1.3 on 2025-01-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0089_cotizacion_egresosmes1_cotizacion_egresosmes2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="movOpcion",
            field=models.CharField(
                choices=[
                    ("usar_valor", "Usar valor"),
                    ("ingresar_manual", "Ingresar manual"),
                ],
                default="ingresar_manual",
                max_length=20,
            ),
        ),
    ]
