# Generated by Django 5.1.3 on 2025-01-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0090_cotizacion_movopcion"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="averageIngresos",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
