# Generated by Django 5.1.3 on 2025-02-03 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0092_cotizacion_tasainteres_alter_cotizacion_oficial_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CotizacionDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("documento", models.FileField(upload_to="documentos_cotizacion/")),
                ("nombre", models.CharField(max_length=255, null=True)),
                ("fecha", models.DateField(auto_now_add=True)),
                (
                    "cotizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pacifico.cotizacion",
                    ),
                ),
            ],
        ),
    ]
