# Generated by Django 5.1.3 on 2025-02-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0093_cotizaciondocumento"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cotizaciondocumento",
            old_name="nombre",
            new_name="tipo_documento",
        ),
        migrations.AddField(
            model_name="cotizaciondocumento",
            name="observaciones",
            field=models.TextField(blank=True, null=True),
        ),
    ]
