# Generated by Django 5.1.3 on 2025-02-03 22:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0094_rename_nombre_cotizaciondocumento_tipo_documento_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="another_boolean_field",
            new_name="pruebaFuncionalidades",
        ),
    ]
