# Generated by Django 5.1.3 on 2025-02-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "pacifico",
            "0095_rename_another_boolean_field_userprofile_pruebafuncionalidades",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizaciondocumento",
            name="size",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
