# Generated by Django 5.1.3 on 2025-02-08 23:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0096_cotizaciondocumento_size_userprofile_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="profile_picture",
        ),
    ]
