# Generated by Django 5.1.3 on 2025-02-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0097_remove_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="tipoPrestamo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("auto", "Préstamo de Auto"),
                    ("personal", "Préstamo Personal"),
                ],
                default="",
                max_length=20,
                null=True,
            ),
        ),
    ]
