# Generated by Django 5.1.3 on 2025-02-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0098_cotizacion_tipoprestamo"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="pagaDiciembre",
            field=models.CharField(
                blank=True,
                choices=[("NO PAGA", "No paga"), ("SI PAGA", "Si paga")],
                default="NO PAGA",
                max_length=10,
                null=True,
            ),
        ),
    ]
