# Generated by Django 5.1.3 on 2025-02-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0100_alter_cotizacion_pagadiciembre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotizacion",
            name="pagaDiciembre",
            field=models.CharField(
                blank=True,
                choices=[("NO", "NO"), ("SI", "SI")],
                default="NO",
                max_length=10,
                null=True,
            ),
        ),
    ]
