# Generated by Django 5.1.3 on 2025-02-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0101_alter_cotizacion_pagadiciembre"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="porServDesc",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="selectDescuento",
            field=models.CharField(
                blank=True,
                choices=[("Y", "Y"), ("N", "N")],
                default="N",
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="cantPagosSeguro",
            field=models.IntegerField(blank=True, default=12, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="kilometrajeAuto",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="mes0",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="mes1",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="mes10",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="mes11",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="mes2",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="mes3",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="mes4",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="mes5",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="mes6",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="mes7",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="mes8",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="mes9",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="mesesFinanciaSeguro",
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="montoanualSeguro",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="nuevoAuto",
            field=models.CharField(
                blank=True,
                choices=[("AUTO NUEVO", "Auto Nuevo"), ("AUTO USADO", "Auto Usado")],
                default="AUTO NUEVO",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="transmisionAuto",
            field=models.CharField(
                blank=True,
                choices=[("MANUAL", "Manual"), ("AUTOMÁTICO", "Automático")],
                default="AUTOMÁTICO",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="valorAuto",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
