# Generated by Django 5.1.3 on 2025-03-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0102_cotizacion_porservdesc_cotizacion_selectdescuento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotizacion",
            name="cashback",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
