# Generated by Django 5.1.3 on 2025-03-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0103_alter_cotizacion_cashback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotizacion",
            name="abono",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="abonoPorcentaje",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="auxMonto2",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="averageIngresos",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="bonosDcto",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="bonosMonto",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="calcComiCierreFinal",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="calcMontoNotaria",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="calcMontoTimbres",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="cartera",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CONTRALORÍA", "CONTRALORÍA"),
                    ("EMP. CSS", "EMP. CSS"),
                    ("AUTÓNOMAS", "AUTÓNOMAS"),
                    ("ACP", "ACP"),
                    ("JUBILADO CSS", "JUBILADO CSS"),
                    ("EMP. PRIVADA", "EMP. PRIVADA"),
                    ("JUBILADO DE LA ZONA", "JUBILADO DE LA ZONA"),
                    ("JUBI ACTIVO CONTRALORIA", "JUBI ACTIVO CONTRALORIA"),
                    ("JUBI ACTIVO CSS", "JUBI ACTIVO CSS"),
                    ("JUBILADO CONTRALORIA", "JUBILADO CONTRALORIA"),
                    ("JUBI ACTIVO AUTÓNOMA", "JUBI ACTIVO AUTÓNOMA"),
                    ("JUBILADO RIESGOS PROF. CSS", "JUBILADO RIESGOS PROF. CSS"),
                    ("INDEPENDIENTE", "INDEPENDIENTE"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="cobonosDcto",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="cobonosMonto",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="codeudorCartera",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CONTRALORÍA", "CONTRALORÍA"),
                    ("EMP. CSS", "EMP. CSS"),
                    ("AUTÓNOMAS", "AUTÓNOMAS"),
                    ("ACP", "ACP"),
                    ("JUBILADO CSS", "JUBILADO CSS"),
                    ("EMP. PRIVADA", "EMP. PRIVADA"),
                    ("JUBILADO DE LA ZONA", "JUBILADO DE LA ZONA"),
                    ("JUBI ACTIVO CONTRALORIA", "JUBI ACTIVO CONTRALORIA"),
                    ("JUBI ACTIVO CSS", "JUBI ACTIVO CSS"),
                    ("JUBILADO CONTRALORIA", "JUBILADO CONTRALORIA"),
                    ("JUBI ACTIVO AUTÓNOMA", "JUBI ACTIVO AUTÓNOMA"),
                    ("JUBILADO RIESGOS PROF. CSS", "JUBILADO RIESGOS PROF. CSS"),
                    ("INDEPENDIENTE", "INDEPENDIENTE"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="codeudorCedula",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="codeudorEmpresa",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="codeudorEstabilidad",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="codeudorIngresos",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="codeudorLicencia",
            field=models.CharField(
                blank=True,
                choices=[("NO", "No"), ("SI", "Si")],
                default="SI",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="codeudorNombre",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="codeudorNombreEmpres1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="codeudorNombreEmpres2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="codeudorNombreEmpres3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="codeudorPeriodo1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="codeudorPeriodo2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="codeudorPeriodo3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="codeudorPosicion",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="codeudorReferenciasAPC",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BUENAS", "BUENAS"),
                    ("REGULARES", "REGULARES"),
                    ("MALAS", "MALAS"),
                    ("PESIMAS", "PESIMAS"),
                    ("SIN REFERENCIAS", "SIN REFERENCIAS"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="codeudorSalario1",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="codeudorSalario2",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="codeudorSalario3",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="codirOtros1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="codirOtros2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="codirOtros3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="codirOtros4",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="codirOtrosDcto1",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="codirOtrosDcto2",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="codirOtrosDcto3",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="codirOtrosDcto4",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="codirOtrosMonto1",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="codirOtrosMonto2",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="codirOtrosMonto3",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="codirOtrosMonto4",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="cohorasExtrasDcto",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="cohorasExtrasMonto",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="cootrosDcto",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="cootrosMonto",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="copagoVoluntario1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="copagoVoluntario2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="copagoVoluntario3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="copagoVoluntario4",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="copagoVoluntario5",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="copagoVoluntario6",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="copagoVoluntarioDcto1",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="copagoVoluntarioDcto2",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="copagoVoluntarioDcto3",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="copagoVoluntarioDcto4",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="copagoVoluntarioDcto5",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="copagoVoluntarioDcto6",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="copagoVoluntarioMonto1",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="copagoVoluntarioMonto2",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="copagoVoluntarioMonto3",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="copagoVoluntarioMonto4",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="copagoVoluntarioMonto5",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="copagoVoluntarioMonto6",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="coporSalarioNeto",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="copraaDcto",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="copraaMonto",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="coprimaDcto",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="coprimaMonto",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="cosalarioBaseMensual",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="cosalarioNeto",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="cosalarioNetoActual",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="cosiacapDcto",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="cosiacapMonto",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="cototalDescuentoDirecto",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="cototalDescuentosLegales",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="cototalPagoVoluntario",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="dirOtros1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="dirOtros2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="dirOtros3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="dirOtros4",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="dirOtrosDcto1",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="dirOtrosDcto2",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="dirOtrosDcto3",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="dirOtrosDcto4",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="dirOtrosMonto1",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="dirOtrosMonto2",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="dirOtrosMonto3",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="dirOtrosMonto4",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="egresosMes1",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="egresosMes2",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="egresosMes3",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="egresosMes4",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="egresosMes5",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="egresosMes6",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="horasExtrasDcto",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="horasExtrasMonto",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="ingresos",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="ingresosMes1",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="ingresosMes2",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="ingresosMes3",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="ingresosMes4",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="ingresosMes5",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="ingresosMes6",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="licencia",
            field=models.CharField(
                blank=True,
                choices=[("NO", "No"), ("SI", "Si")],
                default="SI",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="manejo_5porc",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="marca",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="modelo",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="montoManejoT",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="monto_manejo_b",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="movOpcion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("usar_valor", "Usar valor"),
                    ("ingresar_manual", "Ingresar manual"),
                ],
                default="ingresar_manual",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="movPrimerMes",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ENERO", "ENERO"),
                    ("FEBRERO", "FEBRERO"),
                    ("MARZO", "MARZO"),
                    ("ABRIL", "ABRIL"),
                    ("MAYO", "MAYO"),
                    ("JUNIO", "JUNIO"),
                    ("JULIO", "JULIO"),
                    ("AGOSTO", "AGOSTO"),
                    ("SEPTIEMBRE", "SEPTIEMBRE"),
                    ("OCTUBRE", "OCTUBRE"),
                    ("NOVIEMBRE", "NOVIEMBRE"),
                    ("DICIEMBRE", "DICIEMBRE"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="nombreEmpresa",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="otrosDcto",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="otrosMonto",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="pagoVoluntario1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="pagoVoluntario2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="pagoVoluntario3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="pagoVoluntario4",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="pagoVoluntario5",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="pagoVoluntario6",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="pagoVoluntarioDcto1",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="pagoVoluntarioDcto2",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="pagoVoluntarioDcto3",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="pagoVoluntarioDcto4",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="pagoVoluntarioDcto5",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="pagoVoluntarioDcto6",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="pagoVoluntarioMonto1",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="pagoVoluntarioMonto2",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="pagoVoluntarioMonto3",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="pagoVoluntarioMonto4",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="pagoVoluntarioMonto5",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="pagoVoluntarioMonto6",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="perfilUniversitario",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="porSalarioNeto",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="porSalarioNetoCompleto",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="posicion",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="praaDcto",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="praaMonto",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="primaDcto",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="primaMonto",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="r1",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="referenciasAPC",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BUENAS", "BUENAS"),
                    ("REGULARES", "REGULARES"),
                    ("MALAS", "MALAS"),
                    ("PESIMAS", "PESIMAS"),
                    ("SIN REFERENCIAS", "SIN REFERENCIAS"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="salarioBaseMensual",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="salarioNeto",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="salarioNetoActual",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="salarioNetoActualCompleto",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="salarioNetoCompleto",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="siacapDcto",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="siacapMonto",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="tablaTotalFeci",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="tablaTotalInteres",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="tablaTotalMontoCapital",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="tablaTotalPagos",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="tablaTotalSeguro",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="tasaBruta",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="tasaEstimada",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="tiempoServicio",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="totalDescuentoDirecto",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="totalDescuentosLegales",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="totalDescuentosLegalesCompleto",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="totalIngresosAdicionales",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="totalIngresosMensualesCompleto",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="totalPagoVoluntario",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="wrkLetraSeguro",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="wrkLetraSinSeguros",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="wrkMontoLetra",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="yearCarro",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="yearsFinanciamiento",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
