# Generated by Django 5.1.3 on 2025-03-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0104_alter_cotizacion_abono_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="primerMes",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ENERO", "ENERO"),
                    ("FEBRERO", "FEBRERO"),
                    ("MARZO", "MARZO"),
                    ("ABRIL", "ABRIL"),
                    ("MAYO", "MAYO"),
                    ("JUNIO", "JUNIO"),
                    ("JULIO", "JULIO"),
                    ("AGOSTO", "AGOSTO"),
                    ("SEPTIEMBRE", "SEPTIEMBRE"),
                    ("OCTUBRE", "OCTUBRE"),
                    ("NOVIEMBRE", "NOVIEMBRE"),
                    ("DICIEMBRE", "DICIEMBRE"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="tipoProrrateo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("horas_extras", "Horas Extras"),
                    ("prima_produccion", "Prima de Producción"),
                ],
                default="horas_extras",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="coporSalarioNetoCompleto",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="cosalarioNetoActualCompleto",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="cosalarioNetoCompleto",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="cototalDescuentosLegalesCompleto",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="cototalIngresosAdicionales",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="cototalIngresosMensualesCompleto",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
