# Generated by Django 5.1.3 on 2025-03-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "pacifico",
            "0105_alter_cliente_primermes_alter_cliente_tipoprorrateo_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="aplicaPromocion",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="primerMes",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ENERO", "ENERO"),
                    ("FEBRERO", "FEBRERO"),
                    ("MARZO", "MARZO"),
                    ("ABRIL", "ABRIL"),
                    ("MAYO", "MAYO"),
                    ("JUNIO", "JUNIO"),
                    ("JULIO", "JULIO"),
                    ("AGOSTO", "AGOSTO"),
                    ("SEPTIEMBRE", "SEPTIEMBRE"),
                    ("OCTUBRE", "OCTUBRE"),
                    ("NOVIEMBRE", "NOVIEMBRE"),
                    ("DICIEMBRE", "DICIEMBRE"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="tipoProrrateo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("horas_extras", "Horas Extras"),
                    ("prima_produccion", "Prima de Producción"),
                ],
                default="horas_extras",
                max_length=20,
            ),
        ),
    ]
