# Generated by Django 5.1.3 on 2025-03-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0106_cotizacion_aplicapromocion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotizacion",
            name="mesesFinanciaSeguro",
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
