# Generated by Django 5.1.3 on 2025-03-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0107_alter_cotizacion_mesesfinanciaseguro"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="rol",
            field=models.CharField(
                choices=[
                    ("Oficial", "Oficial"),
                    ("Administrador", "Administrador"),
                    ("Supervisor", "Supervisor"),
                ],
                default="Oficial",
                max_length=20,
            ),
        ),
    ]
