# Generated by Django 5.1.3 on 2025-03-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0108_userprofile_rol"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
