# Generated by Django 5.1.3 on 2025-03-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0109_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotizacion",
            name="pagaDiciembre",
            field=models.CharField(
                blank=True,
                choices=[("NO", "NO"), ("SI", "SI")],
                default="SI",
                max_length=10,
                null=True,
            ),
        ),
    ]
