# Generated by Django 5.1.3 on 2025-03-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0110_alter_cotizacion_pagadiciembre"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="vendedorTipo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SIN VENDEDOR", "SIN VENDEDOR"),
                    ("EXTERNO", "EXTERNO"),
                    ("CHISPA", "CHISPA"),
                    ("INTERNO", "INTERNO"),
                    ("SATELITE", "SATELITE"),
                    ("AGENCIAS", "AGENCIAS"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
