# Generated by Django 5.1.3 on 2025-03-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0111_cotizacion_vendedortipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotizacion",
            name="vendedorComision",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
    ]
