# Generated by Django 5.1.3 on 2025-03-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0112_alter_cotizacion_vendedorcomision"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="vendedorComisionPorcentaje",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
    ]
