# Generated by Django 5.1.3 on 2025-03-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0113_cotizacion_vendedorcomisionporcentaje"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="vendedorOtroComision",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="vendedorOtroPorcentaje",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
