# Generated by Django 5.1.3 on 2025-04-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0115_alter_cotizacion_oficial_alter_userprofile_oficial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="cancDescripcion1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="cancDescripcion2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="cancDescripcion3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="cancDescripcion4",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="cancDescripcion5",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="cancMensualidad1",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="cancMensualidad2",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="cancMensualidad3",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="cancMensualidad4",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="cancMensualidad5",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="cancMonto1",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="cancMonto2",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="cancMonto3",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="cancMonto4",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="cancMonto5",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="pagaDiciembre",
            field=models.CharField(
                blank=True,
                choices=[("NO", "NO"), ("SI", "SI")],
                default="NO",
                max_length=10,
                null=True,
            ),
        ),
    ]
