# Generated by Django 5.1.3 on 2025-04-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0116_cotizacion_cancdescripcion1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="cancRefiSaldo",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
