# Generated by Django 5.1.3 on 2025-04-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0117_cotizacion_cancrefisaldo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotizacion",
            name="cedulaCliente",
            field=models.CharField(default="", max_length=20, null=True),
        ),
    ]
