# Generated by Django 5.1.3 on 2025-04-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacifico", "0120_remove_cliente_apcpi_remove_cliente_apcscore_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="jubilado",
            field=models.CharField(
                blank=True,
                choices=[("SI", "Si"), ("NO", "No")],
                default="NO",
                max_length=10,
                null=True,
            ),
        ),
    ]
