# Generated by Django 5.1.3 on 2025-05-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacifico', '0122_alter_cotizacion_oficial_alter_userprofile_oficial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='cancelaciones1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='cancelaciones2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='cancelaciones3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='cancelaciones4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='cancelaciones5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='cancelaciones6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='deducciones1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='deducciones2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='deducciones3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='deducciones4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='deducciones5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='deducciones6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='hipotecaDescuentoDir',
            field=models.CharField(blank=True, choices=[('NO', 'No'), ('SI', 'Si')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='letraDepende',
            field=models.CharField(blank=True, choices=[('NO', 'No'), ('SI', 'Si')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='letraFaje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='letraHipoteca1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='letraHipoteca2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='tieneEmbargo',
            field=models.CharField(blank=True, choices=[('NO', 'No'), ('SI', 'Si')], max_length=2, null=True),
        ),
    ]
