# Generated by Django 5.1.3 on 2025-05-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacifico', '0123_cotizacion_cancelaciones1_cotizacion_cancelaciones2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='apcScore',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='apcScaore',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='apcPI',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
