# Generated by Django 5.1.3 on 2025-05-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacifico', '0124_remove_cotizacion_apcscore_cotizacion_apcscaore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='tasaInteres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
