# Generated by Django 5.1.3 on 2025-05-23 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacifico', '0125_alter_cotizacion_tasainteres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizacion',
            old_name='apcScaore',
            new_name='apcScore',
        ),
    ]
