# Generated by Django 5.1.3 on 2025-05-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacifico', '0126_rename_apcscaore_cotizacion_apcscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='tapeLetraPrestamo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
