# Generated by Django 5.1.3 on 2025-05-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacifico', '0127_cotizacion_tapeletraprestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='cancelarEmbargo',
            field=models.CharField(blank=True, choices=[('NO', 'No'), ('SI', 'Si')], max_length=2, null=True),
        ),
    ]
