# Generated by Django 5.1.3 on 2025-06-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacifico', '0130_cotizacion_tapesalariobrutomensual'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='plazoInteres',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
