# Generated by Django 5.1.3 on 2025-06-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacifico', '0131_cotizacion_plazointeres'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='montoServDesc',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
