# Generated by Django 5.1.3 on 2025-06-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacifico', '0132_cotizacion_montoservdesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='fechaVencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
