# Generated by Django 5.1.3 on 2025-06-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacifico', '0133_cotizacion_fechavencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='tapeCapacidad50',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='tapeLimiteConHipoteca',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='tapeLimiteSinHipoteca',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='tapeUtilizado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
