# Generated by Django 5.1.3 on 2025-06-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacifico', '0134_cotizacion_tapecapacidad50_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='oficial',
            field=models.CharField(blank=True, choices=[('TAIRA DE OBALDIA', 'TAIRA DE OBALDIA'), ('GERALDINE RODRIGUEZ', 'GERALDINE RODRIGUEZ'), ('BLANCA VERGARA', 'BLANCA VERGARA'), ('MICHELLE SANTANA', 'MICHELLE SANTANA'), ('SHARLEN SAMANIEGO', 'SHARLEN SAMANIEGO'), ('ISIS BARRIA', 'ISIS BARRIA'), ('ILSA JIMÉNEZ', 'ILSA JIMÉNEZ'), ('MELISSA VEGA', 'MELISSA VEGA'), ('ESTEFANI FORD', 'ESTEFANI FORD'), ('CHARLEENE CARRERA', 'CHARLEENE CARRERA'), ('INISHELL MOSQUERA', 'INISHELL MOSQUERA'), ('JEMIMA CASTILLO', 'JEMIMA CASTILLO'), ('KENIA SIERRA', 'KENIA SIERRA'), ('YARINETH SANCHEZ', 'YARINETH SANCHEZ'), ('AMARELIS ALTAMIRANDA', 'AMARELIS ALTAMIRANDA'), ('DAVID ARAUZ', 'DAVID ARAUZ'), ('KRISTY KING', 'KRISTY KING'), ('YAJANIS CONCEPCIÓN', 'YAJANIS CONCEPCIÓN'), ('YEZKA AVILA', 'YEZKA AVILA'), ('MIGDALIA TEJEIRA', 'MIGDALIA TEJEIRA'), ('HANNY CISNEROS', 'HANNY CISNEROS'), ('YITZEL LÓPEZ', 'YITZEL LÓPEZ'), ('NELLY CAMAÑO', 'NELLY CAMAÑO'), ('DEYDA SALDAÑA', 'DEYDA SALDAÑA'), ('JAVIER CASTILLO', 'JAVIER CASTILLO'), ('ELINA DÍAZ', 'ELINA DÍAZ'), ('YARKELIS REYES', 'YARKELIS REYES'), ('STEPHANY SANDOVAL', 'STEPHANY SANDOVAL'), ('MARICRUZ ARMUELLES', 'MARICRUZ ARMUELLES'), ('LARISSA MARCIAGA', 'LARISSA MARCIAGA'), ('SHELUNSKA MASA', 'SHELUNSKA MASA'), ('ARGELIS GOMEZ', 'ARGELIS GOMEZ'), ('ROSMERY ANDRADE', 'ROSMERY ANDRADE'), ('ANDRES RODRIGUEZ', 'ANDRES RODRIGUEZ'), ('ODESSA TEJEIRA', 'ODESSA TEJEIRA'), ('JAVIER CASTILLO', 'JAVIER CASTILLO'), ('ROSA FRANCO', 'ROSA FRANCO'), ('YARISBETH ARDINES', 'YARISBETH ARDINES'), ('MELANIE CEDEÑO', 'MELANIE CEDEÑO'), ('YENIFFER MENESES', 'YENIFFER MENESES'), ('ISRAEL CARRERA', 'ISRAEL CARRERA'), ('LUIS SAMANIEGO', 'LUIS SAMANIEGO'), ('SCARLIN CONTRERAS', 'SCARLIN CONTRERAS'), ('MIGDALIA DE LEÓN', 'MIGDALIA DE LEÓN'), ('IVAN RICHARDS', 'IVAN RICHARDS')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('Oficial', 'Oficial'), ('Administrador', 'Administrador'), ('Supervisor', 'Supervisor'), ('Usuario', 'Usuario')], default='Oficial', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sucursal',
            field=models.CharField(blank=True, choices=[('2', 'COLON'), ('4', 'CASINO'), ('7', 'DAVID'), ('8', 'CHORRERA'), ('11', 'SANTIAGO'), ('13', 'CALLE 50'), ('16', 'CHITRE'), ('17', 'PENONOME')], max_length=255, null=True),
        ),
    ]
