# Generated by Django 5.1.3 on 2025-06-16 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacifico', '0135_alter_userprofile_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='auto_save_cotizaciones',
        ),
    ]
