# Generated by Django 5.1.3 on 2025-06-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacifico', '0135_alter_userprofile_oficial_alter_userprofile_rol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='vendedorImpuesto',
            field=models.CharField(blank=True, choices=[('N', 'N'), ('Y', 'Y')], default='N', max_length=10, null=True),
        ),
    ]
