# Generated by Django 5.1.3 on 2025-06-19 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacifico', '0136_cotizacion_vendedorimpuesto'),
        ('pacifico', '0136_remove_userprofile_auto_save_cotizaciones'),
    ]

    operations = [
    ]
