# Generated by Django 5.1.3 on 2025-06-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacifico', '0139_cliente_added_by_cliente_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cedulaCliente',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
