# Generated by Django 5.1.3 on 2025-06-20 19:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacifico', '0140_alter_cliente_cedulacliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebidaDiligencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('sin_solicitar', 'Sin Solicitar'), ('pendiente', 'Pendiente'), ('completado', 'Completado')], default='sin_solicitar', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(blank=True, null=True)),
                ('busqueda_google', models.FileField(blank=True, null=True, upload_to='diligencia/google/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'])])),
                ('busqueda_registro_publico', models.FileField(blank=True, null=True, upload_to='diligencia/registro_publico/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'])])),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='debida_diligencia', to='pacifico.cliente')),
                ('completado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diligencias_completadas', to=settings.AUTH_USER_MODEL)),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diligencias_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Debida Diligencia',
                'verbose_name_plural': 'Debidas Diligencias',
            },
        ),
    ]
