# Generated by Django 5.1.3 on 2025-06-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacifico', '0141_debidadiligencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('Oficial', 'Oficial'), ('Administrador', 'Administrador'), ('Supervisor', 'Supervisor'), ('Usuario', 'Usuario')], default='Usuario', max_length=20),
        ),
    ]
