# Generated by Django 5.1.3 on 2025-06-30 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacifico', '0142_alter_userprofile_rol'),
        ('pacifico', '0142_userprofile_numerocolaborador_alter_userprofile_rol'),
    ]

    operations = [
    ]
