# Generated by Django 5.1.3 on 2025-06-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacifico', '0143_merge_20250630_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='calcComiCierreFinal',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
