# Generated by Django 5.1.3 on 2025-07-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacifico', '0144_alter_cotizacion_calccomicierrefinal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='etiquetas_oficial',
            field=models.CharField(blank=True, help_text='Etiquetas seleccionadas por la oficial, separadas por coma.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='prioridad',
            field=models.CharField(blank=True, choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], help_text='Prioridad del préstamo', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='dirOtrosMonto2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='patronoCodigo',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
