# Generated by Django 5.1.3 on 2025-07-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacifico', '0145_cotizacion_etiquetas_oficial_cotizacion_prioridad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='etiquetas_oficial',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='prioridad',
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='dirOtrosMonto2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='patronoCodigo',
            field=models.IntegerField(null=True),
        ),
    ]
