# Generated by Django 5.1.3 on 2025-07-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacifico', '0147_alter_cotizacion_oficial_alter_userprofile_oficial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='quinVende',
            field=models.CharField(blank=True, help_text='Agencia que vende el producto', max_length=255, null=True),
        ),
    ]
