# Generated by Django 5.1.3 on 2025-07-17 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacifico', '0148_cotizacion_quinvende'),
    ]

    operations = [
        migrations.CreateModel(
            name='Politicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='sector',
            field=models.CharField(blank=True, choices=[('SECTOR A', 'Sector A'), ('SECTOR B', 'Sector B'), ('SECTOR C', 'Sector C')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='politica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacifico.politicas'),
        ),
    ]
