# Generated by Django 5.1.3 on 2025-08-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacifico', '0149_politicas_cotizacion_sector_cotizacion_politica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('Oficial', 'Oficial'), ('Asistente', 'Asistente'), ('Administrador', 'Administrador'), ('Supervisor', 'Supervisor'), ('Usuario', 'Usuario')], default='Usuario', max_length=20),
        ),
    ]
