# Generated by Django 5.1.3 on 2025-08-07 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pacifico', '0150_alter_userprofile_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_sucursal', models.BooleanField(default=False, help_text='Indica si este grupo representa una sucursal específica')),
                ('sucursal_codigo', models.CharField(blank=True, choices=[('2', 'COLON'), ('4', 'CASINO'), ('7', 'DAVID'), ('8', 'CHORRERA'), ('11', 'SANTIAGO'), ('13', 'CALLE 50'), ('16', 'CHITRE'), ('17', 'PENONOME')], help_text='Código de la sucursal si es_sucursal=True', max_length=10, null=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional del grupo', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el grupo está activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.group')),
            ],
            options={
                'verbose_name': 'Perfil de Grupo',
                'verbose_name_plural': 'Perfiles de Grupos',
            },
        ),
    ]
