# Generated by Django 5.1.3 on 2025-08-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacifico', '0151_groupprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text="Código único de la sucursal (ej: '2', '7', '13')", max_length=10, unique=True)),
                ('nombre', models.CharField(help_text="Nombre de la sucursal (ej: 'COLON', 'DAVID', 'CALLE 50')", max_length=100)),
                ('direccion', models.TextField(blank=True, help_text='Dirección completa de la sucursal', null=True)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email de contacto de la sucursal', max_length=254, null=True)),
                ('activa', models.BooleanField(default=True, help_text='Indica si la sucursal está activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['codigo'],
            },
        ),
    ]
