# Generated by Django 5.1.3 on 2025-08-07 18:46

from django.db import migrations, models
import django.db.models.deletion


def migrar_sucursales_userprofile(apps, schema_editor):
    """
    Migra los códigos de sucursal existentes a referencias del modelo Sucursal
    """
    UserProfile = apps.get_model('pacifico', 'UserProfile')
    Sucursal = apps.get_model('pacifico', 'Sucursal')
    
    # Crear un mapeo de códigos a objetos Sucursal
    sucursales_map = {}
    for sucursal in Sucursal.objects.all():
        sucursales_map[sucursal.codigo] = sucursal
    
    # Actualizar todos los UserProfile
    for user_profile in UserProfile.objects.all():
        if user_profile.sucursal:  # Si tiene un código de sucursal
            sucursal_obj = sucursales_map.get(user_profile.sucursal)
            if sucursal_obj:
                # Actualizar el campo temporal con la referencia
                user_profile.sucursal_nueva = sucursal_obj
                user_profile.save(update_fields=['sucursal_nueva'])


def reversa_migracion_sucursales(apps, schema_editor):
    """
    Revierte la migración copiando de vuelta los códigos
    """
    UserProfile = apps.get_model('pacifico', 'UserProfile')
    
    for user_profile in UserProfile.objects.all():
        if user_profile.sucursal_nueva:
            user_profile.sucursal = user_profile.sucursal_nueva.codigo
            user_profile.save(update_fields=['sucursal'])


class Migration(migrations.Migration):

    dependencies = [
        ('pacifico', '0152_crear_modelo_sucursal'),
    ]

    operations = [
        # Paso 1: Agregar campo temporal
        migrations.AddField(
            model_name='userprofile',
            name='sucursal_nueva',
            field=models.ForeignKey(
                blank=True, 
                help_text='Sucursal a la que pertenece el usuario', 
                null=True, 
                on_delete=django.db.models.deletion.SET_NULL, 
                related_name='usuarios_temp',
                to='pacifico.sucursal'
            ),
        ),
        
        # Paso 2: Migrar datos
        migrations.RunPython(
            migrar_sucursales_userprofile,
            reversa_migracion_sucursales
        ),
        
        # Paso 3: Eliminar campo antiguo
        migrations.RemoveField(
            model_name='userprofile',
            name='sucursal',
        ),
        
        # Paso 4: Renombrar campo nuevo
        migrations.RenameField(
            model_name='userprofile',
            old_name='sucursal_nueva',
            new_name='sucursal',
        ),
    ]
