# Generated by Django 5.1.3 on 2025-08-07 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacifico', '0153_migrar_userprofile_sucursal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='supervisores',
            field=models.ManyToManyField(blank=True, help_text='Supervisores que pueden ver y administrar las solicitudes de este grupo', limit_choices_to={'userprofile__rol__in': ['Supervisor', 'Administrador']}, related_name='grupos_supervisados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sucursal',
            field=models.ForeignKey(blank=True, help_text='Sucursal a la que pertenece el usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacifico.sucursal'),
        ),
    ]
