# Generated by Django 5.1.3 on 2025-08-07 19:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacifico', '0154_agregar_supervisores_grupos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofile',
            name='supervisores',
            field=models.ManyToManyField(blank=True, help_text='Supervisores que pueden ver y administrar las solicitudes de este grupo', related_name='grupos_supervisados', to=settings.AUTH_USER_MODEL),
        ),
    ]
