# Generated by Django 5.1.3 on 2025-08-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacifico', '0157_alter_userprofile_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('Oficial', 'Oficial'), ('Asistente', 'Asistente'), ('Administrador', 'Administrador'), ('Supervisor', 'Supervisor'), ('Analista', 'Analista'), ('Back Office', 'Back Office'), ('Usuario', 'Usuario')], default='Usuario', max_length=20),
        ),
    ]
