# Generated by Django 5.1.3 on 2025-08-15 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacifico', '0158_add_backoffice_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Marca de Auto',
                'verbose_name_plural': 'Marcas de Auto',
            },
        ),
        migrations.CreateModel(
            name='ModeloAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pacifico.marcaauto')),
            ],
            options={
                'verbose_name': 'Modelo de Auto',
                'verbose_name_plural': 'Modelos de Auto',
            },
        ),
    ]
