# Generated by Django 5.1.3 on 2025-06-20 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clienteentrevista',
            old_name='empresa',
            new_name='apellido_casada',
        ),
        migrations.RenameField(
            model_name='clienteentrevista',
            old_name='ocupacion',
            new_name='banco',
        ),
        migrations.RenameField(
            model_name='clienteentrevista',
            old_name='direccion',
            new_name='descripcion_ingreso_1',
        ),
        migrations.RenameField(
            model_name='clienteentrevista',
            old_name='nombre',
            new_name='oficial',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='cedula',
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='acepta_datos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='autoriza_apc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='barrio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='calle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='cargo_pep',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='casa_apto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='conyuge_cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='conyuge_cedula',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='conyuge_ingreso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='conyuge_lugar_trabajo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='conyuge_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='conyuge_telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='descripcion_ingreso_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='descripcion_ingreso_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='direccion_completa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='es_beneficiario_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='es_familiar_pep',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='es_pep',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('CASADO (A)', 'CASADO (A)'), ('UNIDO (A)', 'UNIDO (A)'), ('SOLTERO (A)', 'SOLTERO (A)'), ('VIUDO (A)', 'VIUDO (A)'), ('SEPARADO (A)', 'SEPARADO (A)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='estatura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Estatura (m)'),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='fecha_inicio_trabajo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='frecuencia_pago',
            field=models.CharField(blank=True, choices=[('SEMANAL', 'SEMANAL'), ('QUINCENAL', 'QUINCENAL'), ('MENSUAL', 'MENSUAL')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='institucion_pep',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='jubilado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='monto_ingreso_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='monto_ingreso_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='monto_ingreso_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='nacionalidad',
            field=models.CharField(default='Panamá', max_length=100),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='nivel_academico',
            field=models.CharField(blank=True, help_text='Valores separados por coma para selección múltiple. Ej: PRIMARIA,SECUNDARIA', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='no_dependientes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='nombre_pep',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='origen_fondos',
            field=models.CharField(blank=True, choices=[('LOCAL', 'LOCAL'), ('EXTRANJERO', 'EXTRANJERO')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='parentesco_pep',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='partida_cedula',
            field=models.CharField(default='hola', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='pep_cargo_actual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='pep_cargo_anterior',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='pep_fam_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='pep_fam_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='pep_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='pep_fin_anterior',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='pep_ingreso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='pep_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (lb)'),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='primer_apellido',
            field=models.CharField(default='hola', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='primer_nombre',
            field=models.CharField(default='hola', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='provincia_cedula',
            field=models.CharField(blank=True, choices=[('', '—'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='hola', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='tel_ext',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='tel_trabajo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='tipo_cuenta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='tipo_ingreso_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='tipo_ingreso_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='tipo_ingreso_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='tipo_letra',
            field=models.CharField(blank=True, choices=[('', '—'), ('E', 'E'), ('N', 'N'), ('PE', 'PE'), ('AV', 'AV')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='tipo_producto',
            field=models.CharField(choices=[('Auto', 'Auto'), ('Personal', 'Personal'), ('Hipotecario', 'Hipotecario')], default='hola', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='tipo_trabajo',
            field=models.CharField(blank=True, choices=[('ASALARIADO', 'ASALARIADO'), ('INDEPENDIENTE', 'INDEPENDIENTE'), ('ABOGADO', 'ABOGADO')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='tomo_cedula',
            field=models.CharField(default='hola', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='trabajo_cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='trabajo_direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='trabajo_lugar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clienteentrevista',
            name='email',
            field=models.EmailField(default='hola', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clienteentrevista',
            name='fecha_entrevista',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clienteentrevista',
            name='salario',
            field=models.DecimalField(decimal_places=2, default='hola', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clienteentrevista',
            name='telefono',
            field=models.CharField(default='hola', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OtroIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ingreso', models.CharField(blank=True, choices=[('', '---------'), ('LOCAL', 'LOCAL'), ('EXTRANJERO', 'EXTRANJERO')], default='', max_length=20, null=True)),
                ('fuente', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otros_ingresos', to='workflow.clienteentrevista')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenciaComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('', '---------'), ('COMERCIAL', 'COMERCIAL'), ('CLIENTES', 'CLIENTES')], max_length=100, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('actividad', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('entrevista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias_comerciales', to='workflow.clienteentrevista')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenciaPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('relacion', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('entrevista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias_personales', to='workflow.clienteentrevista')),
            ],
        ),
    ]
