# Generated by Django 5.1.3 on 2025-06-11 14:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clienteentrevista',
            old_name='empresa',
            new_name='banco',
        ),
        migrations.RenameField(
            model_name='clienteentrevista',
            old_name='direccion',
            new_name='descripcion_ingreso_1',
        ),
        migrations.RenameField(
            model_name='clienteentrevista',
            old_name='nombre',
            new_name='oficial',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='cedula',
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='acepta_datos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='anios_servicio',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='autoriza_apc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='barrio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='calle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='cargo_pep',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='casa_apto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='cod_contraloria_1',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='cod_contraloria_2',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='cod_contraloria_3',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='cod_empleado',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='como_se_entero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='conyuge_cedula',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='conyuge_empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='conyuge_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='conyuge_telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='descripcion_ingreso_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='direccion_completa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='es_beneficiario_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='es_familiar_pep',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='es_pep',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='fecha_inicio_trabajo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='forma_pago',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='frecuencia_pago',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='imc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='institucion_pep',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='jubilado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='meses_servicio',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='monto_ingreso_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='monto_ingreso_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='nivel_academico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='no_dependientes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='nombre_pep',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='origen_fondos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='parentesco_pep',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='partida_cedula',
            field=models.CharField(default=99999, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='pep_cargo_actual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='pep_cargo_anterior',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='pep_fam_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='pep_fam_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='pep_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='pep_fin_anterior',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='pep_ingreso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='pep_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='primer_apellido',
            field=models.CharField(default='ApellidoPendiente', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='primer_nombre',
            field=models.CharField(default='apellido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='provincia_cedula',
            field=models.CharField(choices=[('1', 'Panamá'), ('2', 'Coclé'), ('3', 'Colón'), ('4', 'Chiriquí'), ('5', 'Darién'), ('6', 'Herrera'), ('7', 'Los Santos'), ('8', 'Panamá Oeste'), ('9', 'Veraguas'), ('10', 'Guna Yala')], default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='redes_sociales',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='ref1_cel',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='ref1_direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='ref1_empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='ref1_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='ref1_parentesco',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='ref1_tel_resid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='ref1_tel_trab',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='ref2_cel',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='ref2_direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='ref2_empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='ref2_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='ref2_parentesco',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='ref2_tel_resid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='ref2_tel_trab',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='ref3_cel',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='ref3_direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='ref3_empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='ref3_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='ref3_parentesco',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='ref3_tel_resid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='ref3_tel_trab',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='ref_com_actividad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='ref_com_cel',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='ref_com_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='ref_com_saldo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='ref_com_tel',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='ref_com_tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='sector',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='tel_ext',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='tel_residencia',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='tel_trabajo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='telefono2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='tipo_contrato',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='tipo_cuenta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='tipo_ingreso_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='tipo_ingreso_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='tipo_letra',
            field=models.CharField(choices=[('E', 'E'), ('N', 'N'), ('PE', 'PE'), ('AV', 'AV')], default='2000-01-01', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='tipo_producto',
            field=models.CharField(choices=[('Auto', 'Auto'), ('Personal', 'Personal'), ('Hipotecario', 'Hipotecario')], default='2000-01-01', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='tomo_cedula',
            field=models.CharField(default='0000', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='trabajo_cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='trabajo_direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='trabajo_lugar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='venc_cedula',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clienteentrevista',
            name='email',
            field=models.EmailField(default='correo@temporal.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clienteentrevista',
            name='fecha_entrevista',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clienteentrevista',
            name='salario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clienteentrevista',
            name='telefono',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
