# Generated by Django 5.1.3 on 2025-07-05 15:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField()),
                ('sla', models.DurationField(help_text='SLA: Tiempo máximo en esta etapa')),
                ('es_bandeja_grupal', models.BooleanField(default=False)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='workflow.pipeline')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('pipeline', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='CampoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('entero', 'Entero'), ('fecha', 'Fecha'), ('booleano', 'Sí/No')], max_length=20)),
                ('requerido', models.BooleanField(default=False)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos_personalizados', to='workflow.pipeline')),
            ],
        ),
        migrations.CreateModel(
            name='SubEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subestados', to='workflow.etapa')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('etapa', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('asignada_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_asignadas', to=settings.AUTH_USER_MODEL)),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL)),
                ('etapa_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.etapa')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow.pipeline')),
                ('subestado_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.subestado')),
                ('tipo_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow.tiposolicitud')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.etapa')),
                ('usuario_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='workflow.solicitud')),
                ('subestado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.subestado')),
            ],
        ),
        migrations.CreateModel(
            name='PermisoEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puede_ver', models.BooleanField(default=True)),
                ('puede_autoasignar', models.BooleanField(default=True)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='workflow.etapa')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas_permitidas', to='auth.group')),
            ],
            options={
                'unique_together': {('etapa', 'grupo')},
            },
        ),
        migrations.CreateModel(
            name='RequisitoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='requisitos/')),
                ('cumplido', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.requisito')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='workflow.solicitud')),
            ],
            options={
                'unique_together': {('solicitud', 'requisito')},
            },
        ),
        migrations.CreateModel(
            name='RequisitoPipelineTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligatorio', models.BooleanField(default=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.pipeline')),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.requisito')),
                ('tipo_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.tiposolicitud')),
            ],
            options={
                'unique_together': {('pipeline', 'tipo_solicitud', 'requisito')},
            },
        ),
        migrations.CreateModel(
            name='TransicionEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('requiere_permiso', models.BooleanField(default=False)),
                ('etapa_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transiciones_entrada', to='workflow.etapa')),
                ('etapa_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transiciones_salida', to='workflow.etapa')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transiciones', to='workflow.pipeline')),
            ],
            options={
                'unique_together': {('pipeline', 'etapa_origen', 'etapa_destino')},
            },
        ),
        migrations.CreateModel(
            name='ValorCampoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_texto', models.TextField(blank=True, null=True)),
                ('valor_numero', models.FloatField(blank=True, null=True)),
                ('valor_entero', models.IntegerField(blank=True, null=True)),
                ('valor_fecha', models.DateField(blank=True, null=True)),
                ('valor_booleano', models.BooleanField(blank=True, null=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.campopersonalizado')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_personalizados', to='workflow.solicitud')),
            ],
            options={
                'unique_together': {('solicitud', 'campo')},
            },
        ),
    ]
