# Generated by Django 5.1.3 on 2025-06-11 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_rename_empresa_clienteentrevista_banco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='ref1_cel',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='ref1_direccion',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='ref1_empresa',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='ref1_nombre',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='ref1_parentesco',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='ref1_tel_resid',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='ref1_tel_trab',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='ref2_cel',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='ref2_direccion',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='ref2_empresa',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='ref2_nombre',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='ref2_parentesco',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='ref2_tel_resid',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='ref2_tel_trab',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='ref3_cel',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='ref3_direccion',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='ref3_empresa',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='ref3_nombre',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='ref3_parentesco',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='ref3_tel_resid',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='ref3_tel_trab',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='ref_com_actividad',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='ref_com_cel',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='ref_com_nombre',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='ref_com_saldo',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='ref_com_tel',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='ref_com_tipo',
        ),
        migrations.CreateModel(
            name='ReferenciaComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('actividad', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('celular', models.CharField(blank=True, max_length=10, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('entrevista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias_comerciales', to='workflow.clienteentrevista')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenciaPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('parentesco', models.CharField(max_length=100)),
                ('empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('tel_resid', models.CharField(blank=True, max_length=20, null=True)),
                ('tel_trab', models.CharField(blank=True, max_length=20, null=True)),
                ('cel', models.CharField(blank=True, max_length=20, null=True)),
                ('entrevista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias_personales', to='workflow.clienteentrevista')),
            ],
        ),
    ]
