# Generated by Django 5.1.3 on 2025-07-05 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_pipeline_requisito_tiposolicitud_etapa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subestado',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subestados', to='workflow.pipeline'),
        ),
    ]
