# Generated by Django 5.1.3 on 2025-07-05 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_subestado_pipeline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='tipo_solicitud',
        ),
        migrations.CreateModel(
            name='RequisitoPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligatorio', models.BooleanField(default=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos_pipeline', to='workflow.pipeline')),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.requisito')),
            ],
            options={
                'unique_together': {('pipeline', 'requisito')},
            },
        ),
        migrations.DeleteModel(
            name='RequisitoPipelineTipo',
        ),
        migrations.DeleteModel(
            name='TipoSolicitud',
        ),
    ]
