# Generated by Django 5.1.3 on 2025-06-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_remove_clienteentrevista_ref1_cel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteentrevista',
            name='provincia_cedula',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2),
        ),
        migrations.AlterField(
            model_name='clienteentrevista',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1),
        ),
    ]
