# Generated by Django 5.1.3 on 2025-07-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_remove_solicitud_tipo_solicitud_requisitopipeline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='etiquetas_oficial',
            field=models.CharField(blank=True, help_text='Etiquetas separadas por coma para la oficial', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='prioridad',
            field=models.CharField(blank=True, choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], help_text='Prioridad de la solicitud', max_length=10, null=True),
        ),
    ]
