# Generated by Django 5.1.3 on 2025-06-12 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_alter_clienteentrevista_provincia_cedula_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clienteentrevista',
            old_name='forma_pago',
            new_name='apellido_casada',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='anios_servicio',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='meses_servicio',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='ocupacion',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='tipo_contrato',
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='estatura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='nacionalidad',
            field=models.CharField(default='Panamá', max_length=100),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='tipo_trabajo',
            field=models.CharField(blank=True, choices=[('ASALARIADO', 'ASALARIADO'), ('INDEPENDIENTE', 'INDEPENDIENTE'), ('ABOGADO', 'ABOGADO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clienteentrevista',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('CASADO (A)', 'CASADO (A)'), ('UNIDO (A)', 'UNIDO (A)'), ('SOLTERO (A)', 'SOLTERO (A)'), ('VIUDO (A)', 'VIUDO (A)'), ('SEPARADO (A)', 'SEPARADO (A)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clienteentrevista',
            name='frecuencia_pago',
            field=models.CharField(blank=True, choices=[('SEMANAL', 'SEMANAL'), ('QUINCENAL', 'QUINCENAL'), ('MENSUAL', 'MENSUAL')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clienteentrevista',
            name='nivel_academico',
            field=models.CharField(blank=True, help_text='Valores separados por coma para selección múltiple. Ej: PRIMARIA,SECUNDARIA', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clienteentrevista',
            name='origen_fondos',
            field=models.CharField(blank=True, choices=[('LOCAL', 'LOCAL'), ('EXTRANJERO', 'EXTRANJERO')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='OtroIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LOCAL', 'LOCAL'), ('EXTRANJERO', 'EXTRANJERO')], max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otros_ingresos', to='workflow.clienteentrevista')),
            ],
        ),
    ]
