# Generated by Django 5.1.3 on 2025-07-06 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_solicitud_etiquetas_oficial_solicitud_prioridad'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrioridadSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='bg-gray-200 text-gray-800', help_text='Clases Tailwind para el color del badge', max_length=20)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='prioridad',
            field=models.ForeignKey(blank=True, help_text='Prioridad de la solicitud', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='workflow.prioridadsolicitud'),
        ),
    ]
