# Generated by Django 5.1.3 on 2025-06-12 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_rename_forma_pago_clienteentrevista_apellido_casada_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReferenciaComercial',
        ),
    ]
