# Generated by Django 5.1.3 on 2025-07-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_prioridadsolicitud_alter_solicitud_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='prioridad',
            field=models.CharField(blank=True, help_text='Prioridad de la solicitud', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='PrioridadSolicitud',
        ),
    ]
