# Generated by Django 5.1.3 on 2025-06-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_delete_referenciacomercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteentrevista',
            name='gastos_totales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='ingresos_totales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='patrimonio_neto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
