# Generated by Django 5.1.3 on 2025-07-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_alter_solicitud_prioridad_delete_prioridadsolicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='prioridad',
            field=models.CharField(blank=True, choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], help_text='Prioridad de la solicitud', max_length=20, null=True),
        ),
    ]
