# Generated by Django 5.1.3 on 2025-06-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_clienteentrevista_gastos_totales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteentrevista',
            name='otros_ingresos_toggle',
            field=models.BooleanField(default=False),
        ),
    ]
