# Generated by Django 5.1.3 on 2025-06-12 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_clienteentrevista_otros_ingresos_toggle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='imc',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='lugar_nacimiento',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='redes_sociales',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='tel_residencia',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='telefono2',
        ),
    ]
