# Generated by Django 5.1.3 on 2025-06-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_remove_clienteentrevista_imc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteentrevista',
            name='tipo_letra',
            field=models.CharField(blank=True, choices=[('E', 'E'), ('N', 'N'), ('PE', 'PE'), ('AV', 'AV')], max_length=5, null=True),
        ),
    ]
