# Generated by Django 5.1.3 on 2025-07-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_solicitud_cliente_solicitud_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='campopersonalizado',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
