# Generated by Django 5.1.3 on 2025-06-12 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0010_alter_clienteentrevista_tipo_letra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='como_se_entero',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='tipo_producto',
        ),
    ]
