# Generated by Django 5.1.3 on 2025-06-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_remove_clienteentrevista_como_se_entero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenciapersonal',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='referenciapersonal',
            name='parentesco',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
