# Generated by Django 5.1.3 on 2025-07-10 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_solicitudcomentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitoTransicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligatorio', models.BooleanField(default=True, help_text='Si es obligatorio para esta transición')),
                ('mensaje_personalizado', models.TextField(blank=True, help_text='Mensaje personalizado para este requisito', null=True)),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.requisito')),
                ('transicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos_obligatorios', to='workflow.transicionetapa')),
            ],
            options={
                'verbose_name': 'Requisito de Transición',
                'verbose_name_plural': 'Requisitos de Transición',
                'unique_together': {('transicion', 'requisito')},
            },
        ),
    ]
