# Generated by Django 5.1.3 on 2025-06-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0012_alter_referenciapersonal_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenciapersonal',
            name='direccion',
            field=models.CharField(blank=True, default='Sin dirección', max_length=255),
        ),
    ]
