# Generated by Django 5.1.3 on 2025-07-10 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('workflow', '0012_requisitotransicion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoBandeja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puede_ver', models.BooleanField(default=True, help_text='Puede ver las solicitudes en esta bandeja')),
                ('puede_tomar', models.BooleanField(default=True, help_text='Puede tomar solicitudes de esta bandeja')),
                ('puede_devolver', models.BooleanField(default=True, help_text='Puede devolver solicitudes a esta bandeja')),
                ('puede_transicionar', models.BooleanField(default=True, help_text='Puede realizar transiciones desde esta bandeja')),
                ('puede_editar', models.BooleanField(default=False, help_text='Puede editar solicitudes en esta bandeja')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_bandeja', to='workflow.etapa')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bandejas_permitidas', to='auth.group')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bandejas_permitidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso de Bandeja',
                'verbose_name_plural': 'Permisos de Bandeja',
                'unique_together': {('etapa', 'grupo', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='PermisoPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puede_ver', models.BooleanField(default=True, help_text='Puede ver el pipeline y sus solicitudes')),
                ('puede_crear', models.BooleanField(default=False, help_text='Puede crear nuevas solicitudes en este pipeline')),
                ('puede_editar', models.BooleanField(default=False, help_text='Puede editar solicitudes en este pipeline')),
                ('puede_eliminar', models.BooleanField(default=False, help_text='Puede eliminar solicitudes en este pipeline')),
                ('puede_admin', models.BooleanField(default=False, help_text='Puede administrar la configuración del pipeline')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pipelines_permitidos', to='auth.group')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_pipeline', to='workflow.pipeline')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pipelines_permitidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso de Pipeline',
                'verbose_name_plural': 'Permisos de Pipeline',
                'unique_together': {('pipeline', 'grupo', 'usuario')},
            },
        ),
    ]
