# Generated by Django 4.2.7 on 2024-01-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0013_permisobandeja_permisopipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcomentario',
            name='tipo',
            field=models.CharField(choices=[('general', 'General'), ('analista', 'Analista')], default='general', max_length=20),
        ),
    ] 