# Generated by Django 5.1.3 on 2025-06-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0013_alter_referenciapersonal_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteentrevista',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('CASADO (A)', 'Casado (a)'), ('UNIDO (A)', 'Unido (a)'), ('SOLTERO (A)', 'Soltero (a)'), ('VIUDO (A)', 'Viudo (a)'), ('SEPARADO (A)', 'Separado (a)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clienteentrevista',
            name='frecuencia_pago',
            field=models.CharField(blank=True, choices=[('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clienteentrevista',
            name='nivel_academico',
            field=models.CharField(blank=True, help_text='Separar con comas si hay múltiples niveles. Ej: PRIMARIA,SECUNDARIA', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clienteentrevista',
            name='origen_fondos',
            field=models.CharField(blank=True, choices=[('LOCAL', 'Local'), ('EXTRANJERO', 'Extranjero')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clienteentrevista',
            name='tipo_trabajo',
            field=models.CharField(blank=True, choices=[('ASALARIADO', 'Asalariado'), ('INDEPENDIENTE', 'Independiente'), ('ABOGADO', 'Abogado')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='otroingreso',
            name='tipo',
            field=models.CharField(choices=[('LOCAL', 'Local'), ('EXTRANJERO', 'Extranjero')], max_length=20),
        ),
    ]
