# Generated by Django 5.1.3 on 2025-07-12 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0014_add_tipo_to_comentarios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(help_text='Nombre del campo (nombre, cedula, monto, etc.)', max_length=50)),
                ('estado', models.CharField(choices=[('bueno', 'Bueno'), ('malo', 'Malo'), ('sin_calificar', 'Sin Calificar')], default='sin_calificar', max_length=20)),
                ('comentario', models.TextField(blank=True, help_text='Comentario sobre la calificación', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_campos', to='workflow.solicitud')),
                ('usuario', models.ForeignKey(help_text='Usuario que realizó la calificación', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calificación de Campo',
                'verbose_name_plural': 'Calificaciones de Campos',
                'ordering': ['-fecha_modificacion'],
                'unique_together': {('solicitud', 'campo')},
            },
        ),
    ]
