# Generated by Django 5.1.3 on 2025-06-13 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0014_alter_clienteentrevista_estado_civil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='descripcion_ingreso_1',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='descripcion_ingreso_2',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='monto_ingreso_1',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='monto_ingreso_2',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='tipo_ingreso_1',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='tipo_ingreso_2',
        ),
    ]
