# Generated by Django 5.1.3 on 2025-07-17 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0015_calificacioncampo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelComite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField(help_text='Jerarquía (menor = más bajo)')),
            ],
            options={
                'verbose_name': 'Nivel de Comité',
                'verbose_name_plural': 'Niveles de Comité',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudEscalamientoComite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('atendido', models.BooleanField(default=False)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True)),
                ('atendido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalamientos_atendidos', to=settings.AUTH_USER_MODEL)),
                ('nivel_solicitado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow.nivelcomite')),
                ('solicitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalamientos_solicitados', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalamientos_comite', to='workflow.solicitud')),
            ],
            options={
                'verbose_name': 'Escalamiento de Comité',
                'verbose_name_plural': 'Escalamientos de Comité',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='ParticipacionComite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('resultado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('OBSERVACIONES', 'Con Observaciones')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow.nivelcomite')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones_comite', to='workflow.solicitud')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participación en Comité',
                'verbose_name_plural': 'Participaciones en Comité',
                'ordering': ['-fecha_modificacion'],
                'unique_together': {('solicitud', 'nivel', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioNivelComite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.nivelcomite')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario Nivel Comité',
                'verbose_name_plural': 'Usuarios Niveles Comité',
                'unique_together': {('usuario', 'nivel')},
            },
        ),
    ]
