# Generated by Django 5.1.3 on 2025-07-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0015_calificacioncampo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='motivo_consulta',
            field=models.TextField(blank=True, help_text='Motivo de la consulta o observaciones del cliente', null=True),
        ),
    ]
