# Generated by Django 5.1.3 on 2025-06-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0015_remove_clienteentrevista_descripcion_ingreso_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteentrevista',
            name='descripcion_ingreso_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='descripcion_ingreso_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='monto_ingreso_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='monto_ingreso_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='tipo_ingreso_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='tipo_ingreso_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
