# Generated by Django 5.1.3 on 2025-07-17 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0016_nivelcomite_solicitudescalamientocomite_and_more'),
        ('workflow', '0016_solicitud_motivo_consulta'),
    ]

    operations = [
    ]
