# Generated by Django 5.1.3 on 2025-07-18 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0017_merge_20250717_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participacioncomite',
            name='resultado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('OBSERVACIONES', 'Alternativa')], default='PENDIENTE', max_length=20),
        ),
    ]
