# Generated by Django 5.1.3 on 2025-06-13 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0017_remove_clienteentrevista_descripcion_ingreso_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='gastos_totales',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='ingresos_totales',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='otros_ingresos_toggle',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='patrimonio_neto',
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='como_se_entero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='descripcion_ingreso_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='descripcion_ingreso_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='imc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='monto_ingreso_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='monto_ingreso_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='redes_sociales',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='sector',
            field=models.CharField(default='personal', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='tel_residencia',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='telefono2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='tipo_ingreso_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='tipo_ingreso_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='tipo_producto',
            field=models.CharField(choices=[('Auto', 'Auto'), ('Personal', 'Personal'), ('Hipotecario', 'Hipotecario')], default='personal', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clienteentrevista',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('CASADO (A)', 'CASADO (A)'), ('UNIDO (A)', 'UNIDO (A)'), ('SOLTERO (A)', 'SOLTERO (A)'), ('VIUDO (A)', 'VIUDO (A)'), ('SEPARADO (A)', 'SEPARADO (A)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clienteentrevista',
            name='frecuencia_pago',
            field=models.CharField(blank=True, choices=[('SEMANAL', 'SEMANAL'), ('QUINCENAL', 'QUINCENAL'), ('MENSUAL', 'MENSUAL')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clienteentrevista',
            name='nivel_academico',
            field=models.CharField(blank=True, help_text='Valores separados por coma para selección múltiple. Ej: PRIMARIA,SECUNDARIA', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clienteentrevista',
            name='origen_fondos',
            field=models.CharField(blank=True, choices=[('LOCAL', 'LOCAL'), ('EXTRANJERO', 'EXTRANJERO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clienteentrevista',
            name='tipo_letra',
            field=models.CharField(choices=[('E', 'E'), ('N', 'N'), ('PE', 'PE'), ('AV', 'AV')], default='personal', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clienteentrevista',
            name='tipo_trabajo',
            field=models.CharField(blank=True, choices=[('ASALARIADO', 'ASALARIADO'), ('INDEPENDIENTE', 'INDEPENDIENTE'), ('ABOGADO', 'ABOGADO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='otroingreso',
            name='tipo',
            field=models.CharField(choices=[('LOCAL', 'LOCAL'), ('EXTRANJERO', 'EXTRANJERO')], max_length=20),
        ),
        migrations.AlterField(
            model_name='referenciapersonal',
            name='direccion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='referenciapersonal',
            name='parentesco',
            field=models.CharField(default='perosnal', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ReferenciaComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('actividad', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('entrevista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias_comerciales', to='workflow.clienteentrevista')),
            ],
        ),
    ]
