# Generated by Django 5.1.1 on 2025-07-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0018_alter_participacioncomite_resultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarionivelcomite',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones sobre esta asignación', null=True),
        ),
    ]
