# Generated by Django 5.1.3 on 2025-06-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0018_remove_clienteentrevista_gastos_totales_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referenciapersonal',
            old_name='parentesco',
            new_name='relacion',
        ),
        migrations.RemoveField(
            model_name='otroingreso',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='otroingreso',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='referenciapersonal',
            name='cel',
        ),
        migrations.RemoveField(
            model_name='referenciapersonal',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='referenciapersonal',
            name='tel_resid',
        ),
        migrations.RemoveField(
            model_name='referenciapersonal',
            name='tel_trab',
        ),
        migrations.AddField(
            model_name='otroingreso',
            name='fuente',
            field=models.CharField(default='ojo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referenciapersonal',
            name='telefono',
            field=models.CharField(default='ojo', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otroingreso',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='referenciapersonal',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
    ]
