# Generated by Django 5.1.3 on 2025-07-22 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('workflow', '0019_add_observaciones_to_usuarionivelcomite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportePersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del reporte', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del reporte', null=True)),
                ('filtros_json', models.JSONField(default=dict, help_text='Filtros aplicados al reporte en formato JSON')),
                ('campos_json', models.JSONField(default=list, help_text='Campos incluidos en el reporte en formato JSON')),
                ('configuracion_json', models.JSONField(default=dict, help_text='Configuración adicional del reporte')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('es_favorito', models.BooleanField(default=False, help_text='Marcar como favorito')),
                ('es_publico', models.BooleanField(default=False, help_text='Compartir con otros usuarios del mismo grupo')),
                ('veces_ejecutado', models.PositiveIntegerField(default=0, help_text='Contador de ejecuciones')),
                ('ultima_ejecucion', models.DateTimeField(blank=True, help_text='Última vez que se ejecutó', null=True)),
                ('grupos_compartidos', models.ManyToManyField(blank=True, related_name='reportes_compartidos', to='auth.group')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_personalizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte Personalizado',
                'verbose_name_plural': 'Reportes Personalizados',
                'ordering': ['-fecha_modificacion'],
            },
        ),
        migrations.CreateModel(
            name='EjecucionReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True)),
                ('parametros_json', models.JSONField(default=dict, help_text='Parámetros usados en la ejecución')),
                ('tiempo_ejecucion', models.FloatField(blank=True, help_text='Tiempo de ejecución en segundos', null=True)),
                ('registros_resultantes', models.PositiveIntegerField(default=0, help_text='Número de registros en el resultado')),
                ('exitosa', models.BooleanField(default=True, help_text='Si la ejecución fue exitosa')),
                ('mensaje_error', models.TextField(blank=True, help_text='Mensaje de error si falló', null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='workflow.reportepersonalizado')),
            ],
            options={
                'verbose_name': 'Ejecución de Reporte',
                'verbose_name_plural': 'Ejecuciones de Reportes',
                'ordering': ['-fecha_ejecucion'],
            },
        ),
    ]
