# Generated by Django 5.1.3 on 2025-07-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0019_add_observaciones_to_usuarionivelcomite'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='como_se_entero',
            field=models.CharField(blank=True, choices=[('Sucursal', 'Sucursal'), ('Ventas externas', 'Ventas externas'), ('Telemercadeo', 'Telemercadeo'), ('Promoción', 'Promoción'), ('Feria', 'Feria'), ('Plan chispa', 'Plan chispa'), ('Carta de saldo', 'Carta de saldo')], help_text='Cómo se enteró del servicio', max_length=50, null=True),
        ),
    ]
