# Generated by Django 5.1.3 on 2025-06-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0020_clienteentrevista_descripcion_ingreso_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='sector',
        ),
        migrations.AlterField(
            model_name='referenciacomercial',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
