# Generated by Django 5.1.3 on 2025-07-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0020_solicitud_como_se_entero'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='apc_no_cedula',
            field=models.CharField(blank=True, help_text='Número de cédula o pasaporte para APC', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='apc_tipo_documento',
            field=models.CharField(blank=True, choices=[('cedula', 'Cédula'), ('pasaporte', 'Pasaporte')], help_text='Tipo de documento para APC', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='descargar_apc_makito',
            field=models.BooleanField(default=False, help_text='Indica si se debe descargar APC con Makito'),
        ),
    ]
