# Generated by Django 5.1.3 on 2025-07-22 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0021_formularioweb'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='cliente_email',
            field=models.EmailField(blank=True, help_text='Email del cliente', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='cliente_telefono',
            field=models.CharField(blank=True, help_text='Teléfono del cliente', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='monto_solicitado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto solicitado', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones adicionales', null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='origen',
            field=models.CharField(blank=True, help_text='Origen de la solicitud (ej: Canal Digital, Presencial, etc.)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='producto_solicitado',
            field=models.CharField(blank=True, help_text='Producto de interés', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='propietario',
            field=models.ForeignKey(blank=True, help_text='Usuario propietario de la solicitud', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_propias', to=settings.AUTH_USER_MODEL),
        ),
    ]
