# Generated by Django 5.1.3 on 2025-06-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0021_remove_clienteentrevista_sector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otroingreso',
            name='tipo_ingreso',
            field=models.CharField(choices=[('LOCAL', 'LOCAL'), ('EXTRANJERO', 'EXTRANJERO')], default='LOCAL', max_length=20),
        ),
    ]
