# Generated by Django 5.1.3 on 2025-06-16 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0022_otroingreso_tipo_ingreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='cod_contraloria_1',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='cod_contraloria_2',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='cod_contraloria_3',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='cod_empleado',
        ),
    ]
