# Generated by Django 5.1.1 on 2025-07-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0022_solicitud_apc_fecha_completado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='apc_archivo',
            field=models.FileField(blank=True, help_text='Archivo APC generado por Makito', null=True, upload_to='apc_files/'),
        ),
    ]
