# Generated by Django 5.1.3 on 2025-07-22 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0022_solicitud_cliente_email_solicitud_cliente_telefono_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formularioweb',
            name='oficial',
        ),
    ]
