# Generated by Django 5.0.7 on 2025-01-27 16:30

from django.db import migrations, models
import re


def update_existing_codigos(apps, schema_editor):
    """
    Actualiza los códigos existentes de solicitudes para usar el formato secuencial
    """
    Solicitud = apps.get_model('workflow', 'Solicitud')
    
    for solicitud in Solicitud.objects.all():
        if solicitud.codigo and '-' in solicitud.codigo:
            # Verificar si ya tiene el formato correcto (PREFIX-ID)
            parts = solicitud.codigo.split('-')
            if len(parts) == 2 and parts[1].isdigit() and int(parts[1]) == solicitud.id:
                # Ya tiene el formato correcto, saltar
                continue
        
        # Generar nuevo código
        pipeline_nombre = solicitud.pipeline.nombre
        pipeline_clean = re.sub(r'[^a-zA-Z0-9]', '', pipeline_nombre)
        pipeline_prefix = pipeline_clean[:3].upper()
        
        if len(pipeline_prefix) < 3:
            pipeline_prefix = pipeline_clean.upper()
        
        nuevo_codigo = f"{pipeline_prefix}-{solicitud.id}"
        solicitud.codigo = nuevo_codigo
        solicitud.save(update_fields=['codigo'])


def reverse_update_codigos(apps, schema_editor):
    """
    Revertir los cambios (no es necesario para este caso)
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0023_add_apc_archivo_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.RunPython(update_existing_codigos, reverse_update_codigos),
    ]
