# Generated by Django 5.1.3 on 2025-06-16 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0023_remove_clienteentrevista_cod_contraloria_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='tel_residencia',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='telefono2',
        ),
    ]
