# Generated by Django 5.1.3 on 2025-06-16 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0024_remove_clienteentrevista_tel_residencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='como_se_entero',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='imc',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='redes_sociales',
        ),
    ]
