# Generated by Django 5.1.3 on 2025-07-22 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0024_add_cliente_nombre_cedula_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCanalDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Configuración Canal Digital', max_length=100)),
                ('activo', models.BooleanField(default=True, help_text='Si esta configuración está activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('etapa_por_defecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones_canal_digital', to='workflow.etapa')),
                ('pipeline_por_defecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones_canal_digital', to='workflow.pipeline')),
            ],
            options={
                'verbose_name': 'Configuración Canal Digital',
                'verbose_name_plural': 'Configuraciones Canal Digital',
                'ordering': ['-fecha_modificacion'],
            },
        ),
    ]
