# Generated by Django 5.1.3 on 2025-06-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0025_remove_clienteentrevista_como_se_entero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteentrevista',
            name='provincia_cedula',
            field=models.CharField(blank=True, choices=[('', '—'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='clienteentrevista',
            name='tipo_letra',
            field=models.CharField(blank=True, choices=[('', '—'), ('E', 'E'), ('N', 'N'), ('PE', 'PE'), ('AV', 'AV')], max_length=5, null=True),
        ),
    ]
