# Generated by Django 5.1.3 on 2025-07-22 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0024_update_codigo_generation'),
        ('workflow', '0025_configuracioncanaldigital'),
    ]

    operations = [
    ]
