# Generated by Django 5.1.3 on 2025-06-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0026_alter_clienteentrevista_provincia_cedula_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clienteentrevista',
            old_name='conyuge_empresa',
            new_name='conyuge_lugar_trabajo',
        ),
        migrations.RemoveField(
            model_name='clienteentrevista',
            name='venc_cedula',
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='conyuge_cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='conyuge_ingreso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='clienteentrevista',
            name='estatura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Estatura (m)'),
        ),
        migrations.AlterField(
            model_name='clienteentrevista',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (lb)'),
        ),
    ]
