# Generated by Django 5.1.3 on 2025-07-24 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0026_merge_20250722_1838'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcionDesplegable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Opción')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Opción de Desplegable',
                'verbose_name_plural': 'Opciones de Desplegable',
                'db_table': 'workflow_opcion_desplegable',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('fecha_comentario', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('comentario_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Comentario por')),
                ('requisito_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='workflow.requisitosolicitud', verbose_name='Requisito de Solicitud')),
            ],
            options={
                'verbose_name': 'Comentario de Documento',
                'verbose_name_plural': 'Comentarios de Documentos',
                'db_table': 'workflow_comentario_documento',
                'ordering': ['-fecha_comentario'],
            },
        ),
        migrations.CreateModel(
            name='CalificacionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('bueno', 'Bueno'), ('malo', 'Malo')], max_length=10, verbose_name='Estado')),
                ('fecha_calificacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('calificado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Calificado por')),
                ('requisito_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='workflow.requisitosolicitud', verbose_name='Requisito de Solicitud')),
                ('opcion_desplegable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.opciondesplegable', verbose_name='Opción Seleccionada')),
            ],
            options={
                'verbose_name': 'Calificación de Documento',
                'verbose_name_plural': 'Calificaciones de Documentos',
                'db_table': 'workflow_calificacion_documento',
                'ordering': ['-fecha_calificacion'],
                'unique_together': {('requisito_solicitud', 'calificado_por')},
            },
        ),
    ]
