# Generated by Django 5.1.3 on 2025-06-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0027_rename_conyuge_empresa_clienteentrevista_conyuge_lugar_trabajo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otroingreso',
            name='tipo_ingreso',
            field=models.CharField(blank=True, choices=[('', '---------'), ('LOCAL', 'LOCAL'), ('EXTRANJERO', 'EXTRANJERO')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='referenciacomercial',
            name='tipo',
            field=models.CharField(blank=True, choices=[('', '---------'), ('COMERCIAL', 'COMERCIAL'), ('CLIENTES', 'CLIENTES')], max_length=100, null=True),
        ),
    ]
