# Generated by Django 5.1.3 on 2025-07-24 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0027_opciondesplegable_comentariodocumento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentariodocumento',
            name='comentario_por',
        ),
        migrations.RemoveField(
            model_name='comentariodocumento',
            name='requisito_solicitud',
        ),
        migrations.CreateModel(
            name='CalificacionDocumentoBackoffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('bueno', 'Bueno'), ('malo', 'Malo')], max_length=10, verbose_name='Estado')),
                ('fecha_calificacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('calificado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Calificado por')),
                ('opcion_desplegable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.opciondesplegable', verbose_name='Opción Seleccionada')),
                ('requisito_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_backoffice', to='workflow.requisitosolicitud', verbose_name='Requisito de Solicitud')),
            ],
            options={
                'verbose_name': 'Calificación de Documento - Backoffice',
                'verbose_name_plural': 'Calificaciones de Documentos - Backoffice',
                'db_table': 'workflow_calificacion_documento_backoffice',
                'ordering': ['-fecha_calificacion'],
                'unique_together': {('requisito_solicitud', 'calificado_por')},
            },
        ),
        migrations.CreateModel(
            name='ComentarioDocumentoBackoffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('fecha_comentario', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('comentario_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Comentario por')),
                ('requisito_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_backoffice', to='workflow.requisitosolicitud', verbose_name='Requisito de Solicitud')),
            ],
            options={
                'verbose_name': 'Comentario de Documento - Backoffice',
                'verbose_name_plural': 'Comentarios de Documentos - Backoffice',
                'db_table': 'workflow_comentario_documento_backoffice',
                'ordering': ['-fecha_comentario'],
            },
        ),
        migrations.DeleteModel(
            name='CalificacionDocumento',
        ),
        migrations.DeleteModel(
            name='ComentarioDocumento',
        ),
    ]
