# Generated by Django 5.1.3 on 2025-07-24 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0028_remove_comentariodocumento_comentario_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteBackoffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('total_documentos', models.PositiveIntegerField(default=0, verbose_name='Total de Documentos')),
                ('documentos_buenos', models.PositiveIntegerField(default=0, verbose_name='Documentos Buenos')),
                ('documentos_malos', models.PositiveIntegerField(default=0, verbose_name='Documentos Malos')),
                ('total_comentarios', models.PositiveIntegerField(default=0, verbose_name='Total de Comentarios')),
                ('total_opciones', models.PositiveIntegerField(default=0, verbose_name='Total de Opciones')),
                ('detalles_calificaciones', models.JSONField(default=list, verbose_name='Detalles de Calificaciones')),
                ('detalles_comentarios', models.JSONField(default=list, verbose_name='Detalles de Comentarios')),
                ('detalles_opciones', models.JSONField(default=list, verbose_name='Detalles de Opciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('generado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_backoffice', to='workflow.solicitud', verbose_name='Solicitud')),
                ('subetapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_backoffice', to='workflow.subestado', verbose_name='Subetapa')),
            ],
            options={
                'verbose_name': 'Reporte - Backoffice',
                'verbose_name_plural': 'Reportes - Backoffice',
                'db_table': 'workflow_reporte_backoffice',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
