# Generated by Django 5.1.3 on 2025-06-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0028_alter_otroingreso_tipo_ingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteentrevista',
            name='provincia_cedula',
            field=models.CharField(blank=True, choices=[('', '—'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='8', max_length=2, null=True),
        ),
    ]
