# Generated by Django 5.1.3 on 2025-07-25 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0029_reportebackoffice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReporteBackoffice',
        ),
    ]
