# Generated by Django 5.1.3 on 2025-07-25 02:58
# Modified to handle existing 'empresa' column

from django.db import migrations, models, connection


def check_column_exists(table_name, column_name):
    """Check if a column exists in a table using SQLite-compatible syntax."""
    with connection.cursor() as cursor:
        try:
            # SQLite doesn't have information_schema, so we use pragma
            cursor.execute("PRAGMA table_info(%s)", [table_name])
            columns = cursor.fetchall()
            # pragma returns: (cid, name, type, notnull, dflt_value, pk)
            return any(column[1] == column_name for column in columns)
        except Exception:
            # Fallback: try to describe the table
            try:
                cursor.execute("SELECT * FROM %s LIMIT 0" % table_name)
                # If we get here, table exists, now check if column exists
                cursor.execute("SELECT %s FROM %s LIMIT 1" % (column_name, table_name))
                return True
            except Exception:
                return False


def add_empresa_field_if_not_exists(apps, schema_editor):
    """Add empresa field only if it doesn't exist."""
    if not check_column_exists('workflow_clienteentrevista', 'empresa'):
        # If column doesn't exist, create it
        ClienteEntrevista = apps.get_model('workflow', 'ClienteEntrevista')
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                ALTER TABLE workflow_clienteentrevista 
                ADD COLUMN empresa VARCHAR(100) NULL
            """)
        print("✅ Added 'empresa' column to workflow_clienteentrevista table")
    else:
        print("ℹ️  Column 'empresa' column already exists in workflow_clienteentrevista table - skipping")


def reverse_add_empresa_field(apps, schema_editor):
    """Remove empresa field if it exists."""
    if check_column_exists('workflow_clienteentrevista', 'empresa'):
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("ALTER TABLE workflow_clienteentrevista DROP COLUMN empresa")
        print("🗑️  Removed 'empresa' column from workflow_clienteentrevista table")


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0030_delete_reportebackoffice'),
    ]

    operations = [
        migrations.RunPython(
            add_empresa_field_if_not_exists,
            reverse_add_empresa_field,
        ),
    ]
