# Generated by Django 5.1.3 on 2025-07-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0030_delete_reportebackoffice'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteentrevista',
            name='empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
