# Generated by Django 5.1.3 on 2025-07-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0031_auto_20250724_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteentrevista',
            name='completada_por_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clienteentrevista',
            name='fecha_completada_admin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
