# Generated by Django 5.1.3 on 2025-07-25 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0032_clienteentrevista_completada_por_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='formulario_general',
            field=models.ForeignKey(blank=True, help_text='Entrevista de cliente asociada a esta solicitud para el Formulario General', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_formulario_general', to='workflow.clienteentrevista'),
        ),
    ]
