# Generated by Django 5.1.3 on 2025-07-25 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0033_solicitud_formulario_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='formulario_general_fecha_asociacion',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando se asoció el formulario general', null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='formulario_general',
            field=models.ForeignKey(blank=True, help_text='Entrevista de cliente asociada como Formulario General', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_asociadas', to='workflow.clienteentrevista'),
        ),
    ]
