# Generated by Django 5.1.3 on 2025-07-25 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0031_auto_20250724_2158_fixed'),
        ('workflow', '0035_remove_solicitud_formulario_general_and_more'),
    ]

    operations = [
    ]
