# Generated by Django 5.2.4 on 2025-07-28 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0036_merge_20250725_1635'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formularioweb',
            name='propietario',
            field=models.ForeignKey(blank=True, help_text='Usuario asignado para gestionar este lead', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Propietario del Lead'),
        ),
    ]
