# Generated by Django 5.1.3 on 2025-07-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0036_merge_20250725_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciondocumentobackoffice',
            name='estado',
            field=models.CharField(choices=[('bueno', 'Bueno'), ('malo', 'Malo'), ('pendiente', 'Pendiente')], max_length=10, verbose_name='Estado'),
        ),
    ]
