# Generated by Django 5.1.3 on 2025-07-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0036_merge_20250725_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='cotizar_sura_makito',
            field=models.BooleanField(default=False, help_text='Indica si se debe cotizar póliza SURA con Makito'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='sura_archivo',
            field=models.FileField(blank=True, help_text='Archivo cotización SURA generado por Makito', null=True, upload_to='sura_files/'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='sura_fecha_completado',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando se completó el proceso SURA', null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='sura_fecha_inicio',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando Makito inició el proceso SURA', null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='sura_fecha_solicitud',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando se solicitó la cotización SURA', null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='sura_no_documento',
            field=models.CharField(blank=True, help_text='Número de documento para SURA', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='sura_observaciones',
            field=models.TextField(blank=True, help_text='Observaciones del proceso SURA', null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='sura_primer_apellido',
            field=models.CharField(blank=True, help_text='Primer apellido del cliente para SURA', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='sura_primer_nombre',
            field=models.CharField(blank=True, help_text='Primer nombre del cliente para SURA', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='sura_segundo_apellido',
            field=models.CharField(blank=True, help_text='Segundo apellido del cliente para SURA', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='sura_segundo_nombre',
            field=models.CharField(blank=True, help_text='Segundo nombre del cliente para SURA', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='sura_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Proceso'), ('completed', 'Completado'), ('error', 'Error')], default='pending', help_text='Estado del proceso SURA con Makito', max_length=20),
        ),
    ]
