# Generated by Django 5.1.3 on 2025-07-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0037_solicitud_cotizar_sura_makito_solicitud_sura_archivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='debida_diligencia_status',
            field=models.CharField(choices=[('no_iniciado', 'No Iniciado'), ('pendiente', 'Pendiente'), ('makito_processing', 'Makito Procesando'), ('completado', 'Completado'), ('error', 'Error')], default='no_iniciado', help_text='Estado del proceso de debida diligencia', max_length=20),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='diligencia_busqueda_google',
            field=models.FileField(blank=True, help_text='Archivo PDF de búsqueda en Google', null=True, upload_to='debida_diligencia/google/'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='diligencia_busqueda_registro_publico',
            field=models.FileField(blank=True, help_text='Archivo PDF de búsqueda en Registro Público', null=True, upload_to='debida_diligencia/registro_publico/'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='diligencia_fecha_completado',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando se completó la debida diligencia', null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='diligencia_fecha_inicio',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando Makito inició el proceso de debida diligencia', null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='diligencia_fecha_solicitud',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando se solicitó la debida diligencia', null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='diligencia_google_fecha_subida',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando se subió el archivo de Google', null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='diligencia_observaciones',
            field=models.TextField(blank=True, help_text='Observaciones del proceso de debida diligencia', null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='diligencia_registro_publico_fecha_subida',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando se subió el archivo de Registro Público', null=True),
        ),
    ]
