# Generated by Django 5.1.3 on 2025-07-30 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0037_add_pendiente_estado_calificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoPendienteAntesFirma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del pendiente (ej: Re/investigación de empresa)', max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del pendiente')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en listas (menor número = mayor prioridad)')),
                ('activo', models.BooleanField(default=True, help_text='Si está activo, aparecerá en el buscador de pendientes')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pendiente Antes de Firma - Catálogo',
                'verbose_name_plural': 'Pendientes Antes de Firma - Catálogo',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PendienteSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('por_hacer', 'Por Hacer'), ('haciendo', 'Haciendo'), ('listo', 'Listo')], default='por_hacer', help_text='Estado actual del pendiente', max_length=20)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True, help_text='Cuándo se agregó el pendiente')),
                ('etapa_agregado', models.CharField(help_text='Etapa en la que se agregó el pendiente', max_length=100)),
                ('subestado_agregado', models.CharField(help_text='Subestado en el que se agregó el pendiente', max_length=100)),
                ('fecha_completado', models.DateTimeField(blank=True, help_text='Cuándo se completó el pendiente', null=True)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True, help_text='Última modificación del pendiente')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el pendiente')),
                ('agregado_por', models.ForeignKey(help_text='Usuario que agregó este pendiente', on_delete=django.db.models.deletion.PROTECT, related_name='pendientes_agregados', to=settings.AUTH_USER_MODEL)),
                ('completado_por', models.ForeignKey(blank=True, help_text='Usuario que marcó el pendiente como completado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pendientes_completados', to=settings.AUTH_USER_MODEL)),
                ('pendiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_asignadas', to='workflow.catalogopendienteantesfirma')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendientes_antes_firma', to='workflow.solicitud')),
                ('ultima_modificacion_por', models.ForeignKey(help_text='Usuario que hizo la última modificación', on_delete=django.db.models.deletion.PROTECT, related_name='pendientes_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pendiente Antes de Firma - Solicitud',
                'verbose_name_plural': 'Pendientes Antes de Firma - Solicitudes',
                'ordering': ['-fecha_agregado'],
                'unique_together': {('solicitud', 'pendiente')},
            },
        ),
    ]
