# Generated by Django 5.1.3 on 2025-07-30 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0038_agregar_pendientes_antes_firma'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaFirma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(help_text='Fecha y hora programada para la firma')),
                ('lugar_firma', models.CharField(choices=[('delivery', 'Delivery'), ('apoyo', 'Apoyo'), ('casa_matriz', 'Casa Matriz')], help_text='Lugar donde se realizará la firma', max_length=20)),
                ('comentarios', models.TextField(help_text='Comentarios adicionales sobre la cita de firma')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación de la cita')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación')),
                ('creado_por', models.ForeignKey(help_text='Usuario que creó la cita', on_delete=django.db.models.deletion.CASCADE, related_name='agendas_firma_creadas', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, help_text='Usuario que modificó la cita por última vez', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendas_firma_modificadas', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(help_text='Solicitud asociada a esta cita de firma', on_delete=django.db.models.deletion.CASCADE, related_name='agendas_firma', to='workflow.solicitud')),
            ],
            options={
                'verbose_name': 'Agenda de Firma',
                'verbose_name_plural': 'Agendas de Firma',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
