# Generated by Django 5.1.3 on 2025-07-28 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0037_formularioweb_propietario'),
        ('workflow', '0038_add_debida_diligencia_fields'),
    ]

    operations = [
    ]
