# Generated by Django 5.1.3 on 2025-07-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0039_merge_20250728_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='debida_diligencia_status',
            field=models.CharField(choices=[('no_iniciado', 'No Iniciado'), ('solicitado', 'Solicitado'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('error', 'Error')], default='no_iniciado', help_text='Estado del proceso de debida diligencia', max_length=20),
        ),
    ]
