# Generated by Django 5.1.3 on 2025-07-30 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0037_add_calificaciondocumentobackoffice'),
        ('workflow', '0037_add_estado_calificacion_documento_backoffice'),
        ('workflow', '0039_agregar_agenda_firma'),
    ]

    operations = [
    ]
