# Generated by Django 5.2.4 on 2025-07-29 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0040_update_diligencia_status_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaRecordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nota', 'Nota'), ('recordatorio', 'Recordatorio')], default='nota', max_length=20)),
                ('titulo', models.CharField(help_text='Título de la nota o recordatorio', max_length=200)),
                ('contenido', models.TextField(help_text='Contenido de la nota o recordatorio')),
                ('fecha_vencimiento', models.DateTimeField(blank=True, help_text='Fecha de vencimiento del recordatorio', null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('vencido', 'Vencido')], default='pendiente', max_length=20)),
                ('prioridad', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], default='Media', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('es_activo', models.BooleanField(default=True, help_text='Si la nota/recordatorio está activo')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_recordatorios', to='workflow.solicitud')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_recordatorios_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota o Recordatorio',
                'verbose_name_plural': 'Notas y Recordatorios',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
