# Generated by Django 5.1.3 on 2025-07-30 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0040_merge_20250730_1234'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciondocumentobackoffice',
            name='fecha_subsanado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de subsanación'),
        ),
        migrations.AddField(
            model_name='calificaciondocumentobackoffice',
            name='subsanado',
            field=models.BooleanField(default=False, help_text='Marca si el documento marcado como malo ha sido subsanado', verbose_name='Subsanado'),
        ),
        migrations.AddField(
            model_name='calificaciondocumentobackoffice',
            name='subsanado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_subsanados_backoffice', to=settings.AUTH_USER_MODEL, verbose_name='Subsanado por'),
        ),
    ]
