# Generated by Django 5.2.4 on 2025-07-29 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0041_notarecordatorio'),
        ('workflow', '0037_solicitud_cotizar_sura_makito_solicitud_sura_archivo_and_more'),
    ]

    operations = [
    ]
