# Generated by Django 5.1.3 on 2025-07-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0042_merge_0041_notarecordatorio_add_sura_vehicle_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='sura_ano_auto',
            field=models.IntegerField(blank=True, help_text='Año del auto para cotización SURA', null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='sura_marca',
            field=models.CharField(blank=True, help_text='Marca del auto para cotización SURA', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='sura_modelo',
            field=models.CharField(blank=True, help_text='Modelo del auto para cotización SURA', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='sura_tipo_documento',
            field=models.CharField(blank=True, choices=[('cedula', 'Cédula'), ('pasaporte', 'Pasaporte')], help_text='Tipo de documento para SURA', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='sura_valor_auto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor del auto para cotización SURA', max_digits=12, null=True),
        ),
    ]
