# Generated by Django 5.1.3 on 2025-07-30 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacifico', '0149_politicas_cotizacion_sector_cotizacion_politica'),
        ('workflow', '0043_solicitud_sura_ano_auto_solicitud_sura_marca_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='es_reconsideracion',
            field=models.BooleanField(default=False, help_text='Indica si esta solicitud está en proceso de reconsideración'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='resultado_consulta',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Alternativa', 'Alternativa'), ('En Comité', 'En Comité')], default='Pendiente', help_text='Resultado de la consulta de crédito', max_length=20),
        ),
        migrations.CreateModel(
            name='ReconsideracionSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reconsideracion', models.PositiveIntegerField(help_text='Número secuencial de reconsideración')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(help_text='Motivo de la reconsideración')),
                ('usar_nueva_cotizacion', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('enviada', 'Enviada'), ('en_revision', 'En Revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('enviada_comite', 'Enviada a Comité')], default='enviada', max_length=20)),
                ('fecha_analisis', models.DateTimeField(blank=True, null=True)),
                ('comentario_analisis', models.TextField(blank=True)),
                ('resultado_consulta_anterior', models.CharField(blank=True, help_text='Resultado de la consulta anterior', max_length=100)),
                ('comentario_consulta_anterior', models.TextField(blank=True, help_text='Comentario de la consulta anterior')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('analizada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconsideraciones_analizadas', to=settings.AUTH_USER_MODEL)),
                ('cotizacion_nueva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconsideraciones_nueva', to='pacifico.cotizacion')),
                ('cotizacion_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconsideraciones_original', to='pacifico.cotizacion')),
                ('solicitada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconsideraciones_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconsideraciones', to='workflow.solicitud')),
            ],
            options={
                'verbose_name': 'Reconsideración de Solicitud',
                'verbose_name_plural': 'Reconsideraciones de Solicitudes',
                'ordering': ['-numero_reconsideracion'],
                'unique_together': {('solicitud', 'numero_reconsideracion')},
            },
        ),
    ]
