# Generated by Django 5.1.3 on 2025-07-30 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0042_add_orden_expediente_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantillaordenexpediente',
            options={'ordering': ['pipeline', 'orden_seccion', 'seccion', 'orden', 'nombre_documento'], 'verbose_name': 'Plantilla de Orden de Expediente', 'verbose_name_plural': 'Plantillas de Orden de Expediente'},
        ),
    ]
