# Generated by Django 5.1.3 on 2025-07-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0044_alter_plantillaordenexpediente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillaordenexpediente',
            name='orden_seccion',
            field=models.PositiveIntegerField(default=1, help_text='Orden de la sección en el expediente'),
        ),
    ]
