# Generated by Django 5.1.3 on 2025-07-31 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0042_agregar_campos_subsanado_pendiente'),
        ('workflow', '0047_historial_backoffice_bandeja_grupal'),
    ]

    operations = [
    ]
