# Generated by Django 5.1.3 on 2025-07-31 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0049_fix_calificaciondocumentobackoffice_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificaciondocumentobackoffice',
            name='pendiente_completado',
        ),
        migrations.RemoveField(
            model_name='calificaciondocumentobackoffice',
            name='subsanado_por_oficial',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='estado_calificacion_documento_backoffice',
        ),
    ]
