# Generated by Django 5.1.3 on 2025-07-31 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0044_solicitud_es_reconsideracion_and_more'),
        ('workflow', '0050_remove_calificaciondocumentobackoffice_pendiente_completado_and_more'),
    ]

    operations = [
    ]
