# Generated by Django 5.1.3 on 2025-08-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0051_merge_20250731_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacioncampo',
            name='resultado_analisis',
            field=models.CharField(blank=True, choices=[('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Alternativa', 'Alternativa')], help_text='Resultado del análisis para comentarios de analista', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='solicitudcomentario',
            name='resultado_analisis',
            field=models.CharField(blank=True, choices=[('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Alternativa', 'Alternativa')], help_text='Resultado del análisis para comentarios de analista', max_length=20, null=True),
        ),
    ]
