# Generated by Django 5.1.3 on 2025-08-06 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0041_agregar_tipo_especial_requisito'),
        ('workflow', '0052_calificacioncampo_resultado_analisis_and_more'),
    ]

    operations = [
    ]
