# Generated by Django 5.1.3 on 2025-08-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0054_actualizar_requisito_tipo_especial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialbackoffice',
            name='tipo_evento',
            field=models.CharField(choices=[('devolucion', 'Devolución a Negocio'), ('calificacion', 'Cambio de Calificación'), ('subestado', 'Cambio de Subestado'), ('entrada_bandeja_grupal', 'Entrada a Bandeja Grupal'), ('asignacion_desde_bandeja_grupal', 'Asignación desde Bandeja Grupal'), ('solicitud_completa', 'Solicitud Marcada como Completa')], max_length=35, verbose_name='Tipo de Evento'),
        ),
    ]
