# Generated by Django 5.1.3 on 2025-08-08 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0056_fix_clienteentrevista_table_production'),
        ('workflow', '0056_safe_clienteentrevista_noop'),
        ('workflow', '0057_replace_fix_clienteentrevista_table'),
    ]

    operations = [
    ]
