# Generated by Django 5.1.3 on 2025-08-09 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0058_emergency_clienteentrevista_noop'),
        ('workflow', '0058_merge_20250808_1750'),
    ]

    operations = [
    ]
