# Generated by Django 5.2.4 on 2025-08-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0059_merge_20250808_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitopipeline',
            name='tipo_prestamo_aplicable',
            field=models.CharField(choices=[('todos', 'Todos los préstamos'), ('personal', 'Solo préstamo personal'), ('auto', 'Solo préstamo de auto')], default='todos', help_text='Tipo de préstamo al que aplica este requisito', max_length=20),
        ),
    ]
