# Generated by Django 5.2.4 on 2025-08-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0060_add_tipo_prestamo_aplicable_to_requisito_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='api_source',
            field=models.CharField(blank=True, help_text='Identificador de la aplicación externa que creó la solicitud', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='creada_via_api',
            field=models.BooleanField(default=False, help_text='Indica si la solicitud fue creada mediante API externa'),
        ),
    ]
