# Generated by Django 5.1.3 on 2025-08-11 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0057_replace_fix_clienteentrevista_table_postgresql'),
        ('workflow', '0061_add_api_tracking_to_solicitud'),
    ]

    operations = [
    ]
