# Generated by Django 5.1.3 on 2025-08-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0062_merge_20250811_0957'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requisitotransicion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='requisitotransicion',
            name='tipo_prestamo_aplicable',
            field=models.CharField(choices=[('todos', 'Todos los préstamos'), ('personal', 'Solo préstamo personal'), ('auto', 'Solo préstamo de auto')], default='todos', help_text='Tipo de préstamo al que aplica este requisito de transición', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='requisitotransicion',
            unique_together={('transicion', 'requisito', 'tipo_prestamo_aplicable')},
        ),
    ]
