# Generated by Django 5.2.4 on 2025-08-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0062_merge_20250811_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='sector',
            field=models.CharField(blank=True, help_text='Sector laboral del cliente', max_length=100, null=True),
        ),
    ]
