# Generated by Django 5.1.3 on 2025-08-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0063_add_tipo_prestamo_aplicable_to_requisito_transicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='transicionetapa',
            name='tipo_prestamo_aplicable',
            field=models.CharField(choices=[('todos', 'Todos los préstamos'), ('personal', 'Solo préstamo personal'), ('auto', 'Solo préstamo de auto')], default='todos', help_text='Tipo de préstamo al que aplica esta transición', max_length=20),
        ),
    ]
