# Generated by Django 5.1.3 on 2025-08-12 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0063_add_sector_field_to_solicitud'),
        ('workflow', '0064_add_tipo_prestamo_aplicable_transicion'),
    ]

    operations = [
    ]
