# Generated by Django 5.1.3 on 2025-08-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0065_merge_20250812_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='subestado',
            name='sla',
            field=models.DurationField(blank=True, help_text='SLA: Tiempo máximo en este subestado', null=True),
        ),
    ]
