# Generated by Django 5.2.4 on 2025-08-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0065_merge_20250812_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='enlace_conversacion',
            field=models.URLField(blank=True, help_text='Enlace a la conversación o chat relacionado con la solicitud', null=True),
        ),
    ]
