# Generated by Django 5.1.3 on 2025-08-12 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0066_add_sla_to_subestado'),
        ('workflow', '0066_solicitud_enlace_conversacion'),
    ]

    operations = [
    ]
