# Generated by Django 5.1.3 on 2025-08-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0067_merge_20250812_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcomentario',
            name='tipo',
            field=models.CharField(choices=[('general', 'General'), ('analista', 'Analista'), ('analista_credito', 'Analista de Crédito'), ('sistema', 'Sistema')], default='general', max_length=20),
        ),
    ]
