# Generated by Django 5.1.3 on 2025-08-15 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0068_alter_solicitudcomentario_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconsideracionPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='Archivo PDF adjunto a la reconsideración', upload_to='reconsideraciones/')),
                ('nombre_original', models.CharField(help_text='Nombre original del archivo', max_length=255)),
                ('contador', models.PositiveIntegerField(help_text='Contador secuencial de PDFs por reconsideración')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('reconsideracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs_adjuntos', to='workflow.reconsideracionsolicitud')),
                ('usuario_subida', models.ForeignKey(help_text='Usuario que subió el archivo', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PDF de Reconsideración',
                'verbose_name_plural': 'PDFs de Reconsideraciones',
                'ordering': ['contador'],
                'unique_together': {('reconsideracion', 'contador')},
            },
        ),
    ]
