# Generated by Django 5.1.3 on 2025-08-15 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0046_add_archivo_adjunto_reconsideracion'),
        ('workflow', '0070_add_archivo_adjunto_reconsideracion'),
    ]

    operations = [
    ]
