# Generated by Django 5.1.3 on 2025-08-15 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0071_merge_20250815_1354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReconsideracionPDF',
        ),
    ]
