# Generated by Django 5.1.3 on 2025-08-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0075_verify_reconsideracion_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconsideracionsolicitud',
            name='archivo_adjunto',
            field=models.FileField(blank=True, help_text='Archivo PDF adjunto a la reconsideración', null=True, upload_to='reconsideraciones/'),
        ),
    ]
