# Generated by Django 5.1.3 on 2025-08-15 23:05
# Modified to be a no-op since archivo_adjunto field already exists from previous migrations

from django.db import migrations


def noop_forward(apps, schema_editor):
    """No operation - archivo_adjunto field already exists from migrations 0073-0075"""
    print("✅ Migration 0076: archivo_adjunto field already handled by previous migrations - no action needed")


def noop_reverse(apps, schema_editor):
    """No operation on reverse"""
    print("✅ Migration 0076 reverse: no action needed")


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0075_verify_reconsideracion_model'),
    ]

    operations = [
        migrations.RunPython(
            noop_forward,
            noop_reverse
        ),
    ]
