# Generated by Django 5.1.3 on 2025-08-16 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0076_reconsideracionsolicitud_archivo_adjunto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncanaldigital',
            name='propietario_por_defecto',
            field=models.ForeignKey(blank=True, help_text='Usuario que será asignado automáticamente como propietario de nuevos formularios del canal digital', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_canal_digital_propietario', to=settings.AUTH_USER_MODEL, verbose_name='Propietario por Defecto'),
        ),
    ]
