# Generated by Django 5.1.3 on 2025-08-15 23:07
# State-only migration to sync Django's migration state with existing database

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0076_reconsideracionsolicitud_archivo_adjunto'),
    ]

    operations = [
        # This operation updates Django's state without touching the database
        # The field already exists in the database from previous migrations
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # No database operations - field already exists
            ],
            state_operations=[
                # State operation - tells Django the field exists
                migrations.AddField(
                    model_name='reconsideracionsolicitud',
                    name='archivo_adjunto',
                    field=models.FileField(blank=True, help_text='Archivo PDF adjunto a la reconsideración', null=True, upload_to='reconsideraciones/'),
                ),
            ]
        )
    ]
