# Generated by Django 5.1.3 on 2025-08-16 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0077_add_propietario_por_defecto_canal_digital'),
        ('workflow', '0077_final_archivo_adjunto_state_fix'),
    ]

    operations = [
    ]
